### ISSUE TITLE
Disabled web mode causes error 404 when leaving preview page.

### ISSUE THREAD

**Issue by themactep** [OpenIPC/majestic#103]
Disabling web mode in majestic leads to error 404 while navigating from preview page to any other page in legacy web on port 85.

To reproduce:
```
killall majestic
yaml-cli -s .system.webAdmin disabled
majestic
````
open http://192.168.1.10:85/cgi-bin/preview.cgi
click openipc logo in header for going to homepage
get error 404 page, see error in majestic output.

![Screenshot from 2023-02-24 00-52-38](https://user-images.githubusercontent.com/37488/221103469-d5c69bdc-00d5-4160-b37b-ae4373c5cddf.png)

```
killall majestic
yaml-cli -s .system.webAdmin enabled
majestic
````
open http://192.168.1.10:85/cgi-bin/preview.cgi
click openipc logo in header for going to homepage
page opens, no error in logs.

![Screenshot from 2023-02-24 00-53-32](https://user-images.githubusercontent.com/37488/221103498-234905e6-9ffc-4982-8538-c7e82d1dda95.png)

**Comment by widgetii** [comment]
Could you please the same with `curl http://192.168.1.10:85/cgi-bin/preview.cgi`, not the browser?

**Comment by mariarti** [comment]
[preview.cgi.curl.txt](https://github.com/OpenIPC/majestic/files/10824665/preview.cgi.curl.txt)
[status.cgi.curl.txt](https://github.com/OpenIPC/majestic/files/10824667/status.cgi.curl.txt)

**Comment by widgetii** [comment]
It seems that curl works as should, is it a browser glitch?
I couldn't reproduce it on my Chrome though

**Comment by mariarti** [comment]
https://user-images.githubusercontent.com/1933140/221196356-fce66a0f-d812-434c-be64-c8cc57b4c97e.mp4

https://user-images.githubusercontent.com/1933140/221196376-a9ef5652-af72-41f8-aa54-a6f04720456b.mp4

**Comment by widgetii** [comment]
As discussed in TG group it's probably httpd redirect issue
