### ISSUE TITLE
Enable real CBR video for H265 encoders

### ISSUE THREAD

**Issue by tipoman9** [OpenIPC/majestic#109]
# Required information

 * Camera board id: Goke7205v200
 * OpenIPC version: February 2023
 * Commit: b650d5503c861eb646959194280ad3dc59866144
 * Branch: master
 * installation method: Built via buildroot
 * modified majestic.yaml: yes

# Issue description
Seems like H265 encoding is always Variable Bit Rate, even when set to Constant Bit Rate. 
When changed  to H264 CBR , it gives constant bitrate as expected.
Such feature will be useful for FPV users , who require a video stream with a bitrate just below the limited radiolink bandwidth in order do get maximum possible quality.

![CBR](https://user-images.githubusercontent.com/97629810/228677364-006c01db-52c7-40a3-af83-d159c7344863.png)

**Comment by widgetii** [comment]
CBR for H265 codec was added, please check if it works in new Majestic build and close the issue

**Comment by tipoman9** [comment]
I confirm it works, tested in gk7205v200 and hi3516ev300.
On Ingenic T31 I had to set these params in the majestic.yaml to make it work as real CBR.
video0:
  minqp: 10 
  maxqp: 45 
  initqp: 10
