### ISSUE TITLE
Majestic not using configured DNS server

### ISSUE THREAD

**Issue by turboproc** [OpenIPC/majestic#115]
Having a very strict firewall in place, I noticed that Majestic is trying to use different DNS servers than configured. Would be great to have this fixed and Majestic simply using the configured DNS server(s).

See logging below:
```
14:45:19  <       majestic> [  levent] libevent_log_cb@22            Nameserver 1.1.1.1:53 has failed: request timed out.
14:45:19  <       majestic> [telemetr] dns_cb@229                    dns_cb result 67, retrying
14:45:19  <       majestic> [telemetr] dns_cb@229                    dns_cb result 70, retrying
14:45:35  <       majestic> [  levent] libevent_log_cb@22            Nameserver 95.217.179.189:53 has failed: request timed out.
14:45:35  <       majestic> [telemetr] dns_cb@229                    dns_cb result 67, retrying
14:45:39  <       majestic> [  levent] libevent_log_cb@22            Nameserver 8.8.8.8:53 has failed: request timed out.
14:45:50  <       majestic> [  levent] libevent_log_cb@22            Nameserver 95.217.179.189:53 is back up
14:45:59  <       majestic> [  levent] libevent_log_cb@22            Nameserver 8.8.8.8:53 is back up
14:46:24  <       majestic> [  levent] libevent_log_cb@22            Nameserver 1.1.1.1:53 is back up
```
It's not necessarily a backdoor, but would be a lot cleaner.

**Comment by brainstorm** [comment]
This is concerning at best :/

Also, speaking of undesired network calls to the internet, when using HLS, Majestic connects to "majestic.torturelabs.com" when the `http://openipc.local/hls` endpoint is used, downloading a [minified javascript](https://majestic.torturelabs.com/main.0a50aa9be0f9f04278c7.js). I have those assets blocked in uBlock:

![Screenshot 2023-08-23 at 10 48 36 pm](https://github.com/OpenIPC/majestic/assets/175587/f9a143b0-047c-4eca-82d0-9c8051122700)

A way around not having to load any remote JS is using `http://openipc.local/video.m3u8` directly. Safari will open it immediately and even have it floating as a PiP (Picture In Picture) live video, much faster than `http://openipc.local/hls` which uses HLS.js and some custom javascript from the torturelabs server (which could potentially be used to inject arbitrary code dynamically on a hostile network)... unfortunately this `.m3u8` workaround doesn't work with Firefox.

**Comment by widgetii** [comment]
There is a disclaimer on the site about gathering metrics, feel free to send a PR to adapt text style (if you think it's so important)

The reason that Majestic is free that we are gathering board information to optimize our builds and get automated feedback about new features and how code is stable. OpenIPC community get streamer for free, and we use community to make sure that we stabilize our product.

If somebody wants to finance opening Majestic source code (or HLS WebAssembly player mentioned before), also feel free to contact me for details
