### ISSUE TITLE
Incorrect starting time and duration of recorded files

### ISSUE THREAD

**Issue by VanrVanr** [OpenIPC/majestic#116]
When I tried to open single files recorded by Majestic with VLC I noticed that the duration and the start of the video is not correct, many files do not begin on 00:00 and their duration is more than configured in Majestic configuration by recording path formula. This leads to other issues when trying to concatenate these files with ffmpeg.

I tried to format SD Card, rebooted the camera and left it so it could record some files (attached to this issue). When I checked the files I noticed that the first file had correct starting time 00:00 and had 00:47 seconds. The second file had wrong starting time, but it was 00:47, the third file seemed to have the starting time 00:47+real duration of the second file and so on. So if the camera records for hours, the last files recorded will have start time and duration completly messed up. Probably there are other issues with the files as well.

Unfortunately I wasn't able to upload as it was in SD Card in zip file because of size limit, so I uploaded each file inside zip. Originally the directory structure was as follows:

2022_12_16_21
|_53.mp4
2023_01_05_17
|_17.mp4
|_18.mp4
|_19.mp4

The firmware was built from sources in december 16, 2022.

The camera model is MJSXJ02HL (hi3518ev300), recording section of majestic.yaml is as follows:
`records:
   enabled: true
   path: /mnt/mmcblk0p1/%Y_%m_%d_%H/%M.mp4
   maxUsage: 95`

Recorded files:
[53.zip](https://github.com/OpenIPC/firmware/files/10357152/53.zip)
[17.zip](https://github.com/OpenIPC/firmware/files/10357115/17.zip)
[18.zip](https://github.com/OpenIPC/firmware/files/10357116/18.zip)
[19.zip](https://github.com/OpenIPC/firmware/files/10357156/19.zip)

**Comment by p0i5k** [comment]
soc: gk7205v200
majestic: ultimate master+69793dc, 2023-08-22

Same behavior:
![image](https://github.com/OpenIPC/majestic/assets/21039610/76c91c5a-daa8-4d24-bad6-a7cd397433a4)
Real file duration is 1 hour, except first
