### ISSUE TITLE
Motion Detection roi

### ISSUE THREAD

**Issue by darkfuncat** [OpenIPC/majestic#117]
Hi all,
Thanks for nice work here.
I am testing with a device xiaomi : hi3518ev300 (hi3516ev200 family), jxf22, 16 MB nor flash, 2.3.05.12-lite, openipc-hi3518ev300
I focus on "In-Camera Motion Detection" feature.
It is working by default (I use MQTT and FTP) but when I try "Regions of Interest" nothing works. Nothing triggered.
I try with whole region 0x0x1920x1080 and some part (half) but nothing.
And if I leave the field empty, it works.
Also I have to reboot between each try, as I noticed that the daemon does not restart properly : when I started, there are 2 processes /usr/sbin/motiondetection.sh, and when I do some update, it adds some process but never kills the existing one. Dont know if it is ok.

**Comment by widgetii** [comment]
Please include your `/etc/majestic.yaml` file without sensitive information

**Comment by darkfuncat** [comment]
Hi @widgetii 
Here is the conf :
`system:
  buffer: 1024
  staticDir: /var/www/majestic
isp:
  iqProfile: /etc/sensors/iq/f23.ini
image:
  mirror: true
  flip: true
  rotate: none
  contrast: 50
  hue: 50
  saturation: 50
  luminance: 50
osd:
  enabled: true
  template: "cam11-void | %F %T %Z"
nightMode:
  enabled: true
  irCutPin1: 70
  irCutPin2: 68
  backlightPin: 54
  dncDelay: 10
records:
  enabled: false
  path: /mnt/mmcblk0p1/%Y/%m/%d/%H/%M.mp4
  maxUsage: 50
video0:
  enabled: true
  codec: h265
  gopSize: 1
video1:
  enabled: false
jpeg:
  enabled: true
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 2048
audio:
  enabled: false
  volume: 70
  srate: 8000
  codec: pcm
  outputEnabled: false
  speakerPin: 55
  speakerPinInvert: false
  voiceEqualizer: common
rtsp:
  enabled: true
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: true
  visualize: true
  debug: true
  skipIn: 0x0x960x1080
ipeye:
  enabled: false
netip:
  enabled: false
  user: admin
  password: 12345
  port: 34567
  snapshots: true
  ignoreSetTime: false
onvif:
  enabled: false
watchdog:
  enabled: true
  timeout: 30
`

**Comment by widgetii** [comment]
It's not a valid YAML

**Comment by darkfuncat** [comment]
I edit. There was formating error with github with leading spaces.

**Comment by widgetii** [comment]
Checked your config on my camera, it works, in logs:

```
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@836      Motion detected in 21 regions, 992x370 -> [2584x1510]
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      1232,388	80,80
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      1400,564	272,114
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      1456,1350	120,96
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      2168,428	168,178
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      2064,404	512,258
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      1896,1374	200,120
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      1856,582	728,242
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      1704,548	64,106
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      1632,564	200,114
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      2336,1430	248,80
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      2456,614	64,104
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      1152,1462	104,48
21:11:20  <hi_motionDetect> [ mdetect] motion_detect_thread@830      1032,1252	320,154
```

Let's see yours

**Comment by darkfuncat** [comment]
Hi, I ve made some tests again.
First I would says that ROI alone IS working. For example if I set to 1080x0x1920x1080 (my cam is 1920x1080), only right part of picture triggers the alarm.
But the EXCLUDE ROI does not work and that is the point here.
Example, if I understand correctly, putting 1080x0x1920x1080 to EXCLUDE ROI should ignore triggers in this zone, but it is not the case.
Sample logs :
````
May 14 00:39:31 openipc-hi3518ev300 user.info majestic[1054]: Motion detected in 1 regions, 1728x0 -> [1872x24]
May 14 00:39:31 openipc-hi3518ev300 user.info majestic[1054]: 1728,0    136,16
May 14 00:39:31 openipc-hi3518ev300 user.info majestic[1054]: Motion detected in 1 regions, 1728x0 -> [1864x16]
May 14 00:39:31 openipc-hi3518ev300 user.info majestic[1054]: 1728,0    136,8
May 14 00:39:31 openipc-hi3518ev300 user.info majestic[1054]: Motion detected in 1 regions, 1728x0 -> [1864x8]
May 14 00:39:41 openipc-hi3518ev300 user.info majestic[1054]: 1080,0    568,670
May 14 00:39:41 openipc-hi3518ev300 user.info majestic[1054]: Motion detected in 1 regions, 1080x0 -> [1648x670]
May 14 00:39:41 openipc-hi3518ev300 user.info majestic[1054]: 1080,0    568,630
May 14 00:39:41 openipc-hi3518ev300 user.info majestic[1054]: Motion detected in 1 regions, 1080x0 -> [1648x630]
````

Note that I do not have same logs as yours, I use "logread" command on my side.
And as always, I must reboot between each change of config which is not comfortable.

**Comment by widgetii** [comment]
Region coordinates are set in format topX, topY, width, height. In your case 1080x0x1920x1080 looks like topX, topY, bottomX, bottomY coordinates, so it's out of image window size.

**Comment by darkfuncat** [comment]
Hi @widgetii 
Thanks for your precision.
Considering format topX, topY, width, height I changed my Region excluded to 960x0x960x1080 (I suppose to be the half right part), and I leave ROI empty.
But with this set, the cam triggers alarm no matter the real move region.
Some logs :
```
May 15 23:20:01 openipc-hi3518ev300 user.info majestic[1074]: Motion detected in 2 regions, 1040x400 -> [1592x834]
May 15 23:20:01 openipc-hi3518ev300 user.info majestic[1074]: 1040,400  8,434
May 15 23:20:01 openipc-hi3518ev300 user.info majestic[1074]: 1528,530  64,214
```
```
May 15 23:28:18 openipc-hi3518ev300 user.info majestic[1074]: Motion detected in 1 regions, 312x0 -> [336x514]
May 15 23:28:18 openipc-hi3518ev300 user.info majestic[1074]: 312,0     24,514
```

**Comment by flyrouter** [comment]
https://github.com/OpenIPC/majestic/issues/28#issuecomment-1776146635
