### ISSUE TITLE
Incorrect video duration in 1 minute files

### ISSUE THREAD

**Issue by bo-skor** [OpenIPC/majestic#119]
# Required information

 * Camera board id: MJSXJ03HL
 * OpenIPC version:     2.3.05.04-lite
 * Commit: 
 * Branch: master
 * Tag:
 * installation method: UART
 * modified majestic.yaml: yes

# Issue description

Если запись видео на SD карту происходит стандартным отрезками по 1 часу, то перемотка работает корректно. Однако если выставить запись файлами по 1 минуте, то длительность отображается некорректно, в части случаев 1 часю Перемотка в таком случае не работает или ведет себя непредсказуемо.

# Expectations

# Steps to reproduce

 1. Включаем запись и заполняем поле `/mnt/mmcblk0p1/%Y/%m/%d/%H/%M.mp4`
 2. Производим запись
 3. Просматриваем записанный материал. Перемотка не работает

# Information to attach

 - [ ] Any relevant log output (`logread -f`)
 - [ *] majestic.yaml configuration (`cat /etc/majestic.yaml`)
 ```
system:
  webAdmin: disabled
  buffer: 1024
  logLevel: DEBUG
image:
  mirror: false
  flip: false
  rotate: none
  contrast: auto
  hue: 50
  saturation: 50
  luminance: auto
osd:
  enabled: true
  template: "%a %e %B %Y %H:%M:%S"
nightMode:
  enabled: true
  nightAPI: false
  backlightPin: 60
  irSensorPinInvert: false
  irCutPin1: 49
  irCutPin2: 50
records:
  enabled: false
  path: /mnt/mmcblk0p1/%Y/%m/%d/%H/%M.mp4
  maxUsage: 95
video0:
  enabled: true
  codec: h265
  rcMode: avbr
  gopMode: smart
  fps: 4
video1:
  enabled: false
jpeg:
  enabled: true
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: false
  volume: auto
  srate: 8000
  speakerPinInvert: false
  outputEnabled: false
  codec: ulaw
rtsp:
  enabled: true
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: true
  visualize: true
  debug: true
  sensitivity: 8
ipeye:
  enabled: false
watchdog:
  enabled: true
  timeout: 10
isp:
  blkCnt: 1
  lowDelay: false
```

**Comment by gtxaspec** [comment]
I have this issue as well:

The duration time of the file created by majestic is incorrect, it seems to be the total time majestic has been running at the time of the file creation, yet the file is supposed to be 1 minute, only:

File created by majestic:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '00.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1iso6mp41
    creation_time   : 2023-08-02T18:00:04.000000Z
    encoder         : Lavf57.83.100
  **Duration: 03:03:28.48, start: 10937.674445, bitrate: 14 kb/s**
    Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 2048x1536, 14 kb/s, 19.77 fps, 20 tbr, 1000k tbn (default)

```

Latest master as of today.
file created by ffmpeg:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/backup/HomeAssistant/media/wyze/record/street/street-2023_07_24-17_36.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf59.16.100
  **Duration: 00:01:00.03, start: 0.000000, bitrate: 2137 kb/s**
  Stream #0:0[0x1]: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, 2006 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
```
