### ISSUE TITLE
HI3518EV200 with JXH62 Invalid Exposure

### ISSUE THREAD

**Issue by matthew-jones-uk** [OpenIPC/majestic#128]
# Required information

 * Camera board id: HI3518EV200
 * OpenIPC version: 2.3.06.30
 * Commit: f5c5bad9
 * Branch: master
 * Tag: 2023-06-30?
 * installation method: manual according to site instructions
 * modified majestic.yaml: no

# Issue description

Video feed not working, possibly due to exposure issues? 

```
00:45:29  <     iq_monitor> [     sdk] monitor_thread@363            Query exposure info
00:45:29  <     iq_monitor> [     sdk] monitor_thread@363            Unknown error code A01C8046
```

# Expectations

Video feed works

# Steps to reproduce

1. Start majestic
2. Try to connect to any video feed

# Information to attach

ezviz C3W camera, can also provide OEM firmware dump if needed

## Logs

[kmsg.log](https://github.com/OpenIPC/majestic/files/11963130/kmsg.log)
[majestic.log](https://github.com/OpenIPC/majestic/files/11963137/majestic.log)

**EDIT:** Possibly a related to https://github.com/OpenIPC/firmware/issues/676. Different sensors, but the same error message.

**Comment by matthew-jones-uk** [comment]
I'm not sure if this is helpful at all, but I've extracted the OEM firmware a bit and there's a `gamma_table.tar.gz`.

Does gamma = exposure?  I've [attached](https://github.com/OpenIPC/majestic/files/11963210/gamma_table.tar.gz) the file if it is helpful.

**Comment by widgetii** [comment]
We don't have such combination of SoC and sensor in our lab, please provide your hardware for tests
