### ISSUE TITLE
Error in preview majestic, SoC GK7205v300, sensor sc223a.

### ISSUE THREAD

**Issue by caltelinf** [OpenIPC/majestic#129]
# Required information

 * Camera board id:2023.02.2
 * OpenIPC version:2.3.07.20
 * Commit:-
 * Branch:-
 * Tag: Goke7205v300, HIVIEW, majestic, sc223a.
 * installation method: Burn utility/Ubuntu, flash u-boot, install firmware Goke7205v300
 * modified majestic.yaml: no
 * cat /dev/kmsg
 * killall majestic
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
   [https://pastebin.com/kBCQ51JT](url)
   Core dump file from /tmp/ , e.g. /tmp/majestic.806.11.1619707881.core
[https://drive.google.com/file/d/13eVPVl_SwJla-68MtQYQhu-g9RfPfbvt/view?usp=sharing](url)
# Issue description

After installing the Goke 7205v300 ultimate 16 NOR firmware, I expected to see the sensor image in the preview tab but nothing was visible, looking for help in the telegram group, they commented that it is a deeper problem within the kernel or sdk .

# Expectations

My only expectation is to see the image from my camera in the browser and be able to connect it to my recorder by onvif and if possible use the audio, microphone and white led lights.

# Steps to reproduce

1.- First use the burn utility with ubuntu to flash ipc u-boot and install the goke7205v300 frimware via tft server.
2.- Then, through the web UI, enter and select the sc223a.i2c image sensor.
3.- Search and select the gpio of the XM boards for the GK7205v300 processor.
4.- View the preview tab.

# Information to attach
[https://pastebin.com/kBCQ51JT](url)

**Comment by widgetii** [comment]
`modified majestic.yaml: no`

It's not a true because according to majestic logs, a lot of settings were changed from default values. Try to roll back into default config and run majestic again

**Comment by VolodymyrHrynevych** [comment]
sc223a not work
Firmware
Version
2.3.10.26-ultimate
Build
master+6e8f923, 2023-10-26
Majestic
master+71d6c43, 2023-10-26

**Comment by widgetii** [comment]
Please provide logs as described above
