### ISSUE TITLE
Feature Request: Allow outgoing configuration options for each video stream

### ISSUE THREAD

**Issue by gtxaspec** [OpenIPC/majestic#130]
Hello OpenIPC Team, I would like to bring up a feature enhancement that could significantly improve the usability and performance of the Majestic product. 

**Problem:**
Currently, when we enable the outgoing unix socket, or udp/rtmp destination, it only allows us to display the stream from the `video0` source. This limits our ability to use the lower-resolution `video1` stream for different applications.

**Why I'm suggesting this:**
In many situations, we need to send the video output from the lower resolution `video1` stream to AI or image recognition programs running directly on the camera for example.

**Benefits:**
Adding this feature would grant users more flexibility, as they could choose to feed either high-resolution or low-resolution video streams to image recognition programs / other video processing programs such as ffmpeg.  Processing the lower resolution stream results in faster recognition with lower performance requirements, in for example, custom programs, or other solutions such as Home Assistant or Frigate.  Additionally, this would also ensure feature consistency with other platforms, enhancing the overall user experience.

**Proposed Changes:**

I suggest relocating the configuration keys from the `outgoing` section to each individual video stream section, like so:

``` 
video0:
  enabled: true
  ...
  udp://IP:port
  unix:/tmp/rtpstream.sock
  rtmps://dc4-1.rtmp.t.me/s/mykey

video1:
  enabled: true
  ...
  udp://IP:port
  unix:/tmp/rtpstream.sock
  rtmps://dc4-1.rtmp.t.me/s/mykey
```
And enabling associated functionality with each video stream.

This simple adjustment would allow each video stream to be independently configured, thus offering much more versatility.

I hope you'll consider this suggestion, as I believe it would make a meaningful difference to many users. 

Thank you for your attention and keep up the great work with this project!

**Comment by Raych89** [comment]
We are testing the FPV version of OpenIPC with on-device image recognition software for autonomous navigation.  The ability to provide low-resolution video via UDP or a Unix socket would be much appreciated.

additionally, we suggest offering low-resolution feeds of the WebRTC/HLS/MP4 endpoints as well.

we hope the developers can add these features soon and eagerly await their implementation in OpenIPC.  cheers.

**Comment by etiaro** [comment]
I see this is closed as completed. How can we setup UDP outgoing stream for video1, then?
