### ISSUE TITLE
bug: if netip not disabled in config, it's automatically enabled.

### ISSUE THREAD

**Issue by gtxaspec** [OpenIPC/majestic#131]
bug:  In majestic.yaml, if netip is not explicitly disabled, for example if:
```
netip:
  enabled: false
```
is missing from the default config (which it is), then the NETIP listener is started when majestic is run:
```
02:57:36  <       majestic> [   netip] netip_start@2055              NETIP server started on port 34567
```

If the maintainers would change the code to default off, or add:
```
netip:
  enabled: false
``` 
to the default config, then the issue would be resolved.  

Still occuring on latest majestic build `master+334110f, 2023-08-20`

**Comment by FlyRouter** [comment]
Fixed
