### ISSUE TITLE
Enable authentication on endpoints

### ISSUE THREAD

**Issue by akanouras** [OpenIPC/majestic#137]
# Required information

 * Camera board id: Xiaomi MJSXJ03HL
 * OpenIPC version: 2.3.10.06
 * Commit: 8f80886
 * Branch: master
 * Tag: 2023-10-06
 * installation method: https://github.com/OpenIPC/device-mjsxj03hl/blob/master/Manual_en.md
 * modified majestic.yaml: yes

# Issue description

I cannot find a way to enable authentication for most Majestic endpoints:

1. JPEG endpoint is enabled, even though `jpeg.enabled: false` is set, and also allows unauthenticated access
2. Audio endpoints can be accessed without authentication
3. Prometheus metrics can also be accessed without authentication

Searching the website, github repos, and general Google queries did not turn up a way to enable authentication.

# Expectations

I would have expected for the above endpoints to return `HTTP/1.1 401 Unauthorized`, like `/night/on` does, for example.

# Steps to reproduce

1. JPEG endpoint:
```
$ curl -s http://192.168.0.10/image.jpg | file -
/dev/stdin: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, comment: "", comment: "", comment: "", comment: "", comment: "", comment: "", baseline, precision 8, 1920x1080, components 3
```

2. Audio endpoints:
```
$ curl -s http://192.168.0.10/audio.opus | ffmpeg -i -
[...]
Input #0, ogg, from 'pipe:':
  Duration: N/A, start: -0.440000, bitrate: N/A
  Stream #0:0: Audio: opus, 48000 Hz, mono, fltp
```

3. Prometheus metrics:
```
$ curl -s http://192.168.0.10/metrics | head -1
# HELP node_uname_info Labeled system information as provided by the uname system call.
```

# Information to attach

 - [ ] Any relevant log output (`logread -f`)
 - [x] majestic.yaml configuration (`cat /etc/majestic.yaml`)
```
system:
  webAdmin: disabled
  buffer: 128
image:
  mirror: false
  flip: false
  rotate: none
  contrast: 50
  hue: 50
  saturation: 50
  luminance: 50
osd:
  enabled: false
  template: "%a %e %B %Y %H:%M:%S %Z"
nightMode:
  enabled: true
  nightAPI: false
  irSensorPinInvert: false
  backlightPin: 60
  irCutPin1: 49
  irCutPin2: 50
records:
  enabled: false
  path: /mnt/mmcblk0p1/%F/%H.mp4
  maxUsage: 95
video0:
  enabled: true
  codec: h265
  size: 1920x1080
  fps: 15
  bitrate: 1024
  gopMode: smart
  rcMode: avbr
video1:
  enabled: false
jpeg:
  enabled: false
  toProgressive: false
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: true
  volume: auto
  srate: 16000
  speakerPinInvert: false
  codec: aac
  outputEnabled: false
rtsp:
  enabled: true
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: false
  visualize: true
  debug: true
ipeye:
  enabled: false
watchdog:
  enabled: true
  timeout: 10
isp:
  lowDelay: true
  rawMode: fast
  blkCnt: 1
```

**Comment by widgetii** [comment]
Let's discuss first how we can do you without breaking existing installations/clients (like using additional options?)

1. Adding system authentication will break WebUI that uses JPEG endpoint for preview
2. For audio endpoints, it seems nothing bad will happen
3. For Prometheus metrics, I think it's better to have it disabled by default

**Comment by akanouras** [comment]
Re Preview, if the WebUI is served through Majestic and HTTP Authentication is used, the browser should use the same credentials for the JPEG endpoint.

Re Prometheus, agreed.

I think a good first step would be to add authentication: attribute to all endpoints in `majestic.yaml`, defaulting to current behaviour for each endpoint, and let the user choose the compromise they prefer.

If that would take too much developer time, including iptables with a basic set of modules in the images would be a reasonable compromise for now.

**Comment by flyrouter** [comment]
Done
