### ISSUE TITLE
Hi3518EV100 streaming RTSP segfaults after a while

### ISSUE THREAD

**Issue by tosa500** [OpenIPC/majestic#139]
# Required information

 * Camera board id: Hi3518EV100
 * OpenIPC version:  2.3.10.22-lite
 * Commit:
 * Branch: stable
 * Tag:
 * installation method: by uboot/tftp
 * modified majestic.yaml: no
 * cat /dev/kmsg
 * killall majestic
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
   Core dump file from /tmp/ , e.g. /tmp/majestic.806.11.1619707881.core

# Issue description

When streaming video to vlc, majestic segfaults after a few minutes - randomly from 1 to 30 minutes

# Expectations
Failure free streaming

# Steps to reproduce

 1. Start majestic - either autostart or from command line
 2. Connect from VLC to stream 0

# Information to attach

[majestic.log](https://github.com/OpenIPC/majestic/files/13299977/majestic.log)
[majestic.11990.11.1699461950.core.zip](https://github.com/OpenIPC/majestic/files/13299994/majestic.11990.11.1699461950.core.zip)

**Comment by flyrouter** [comment]
I don't think you will get an answer to your question in this form, unfortunately this is too broad a question.
VLC is not a panacea, please try other programs to get the stream, disable all unused services in majestic.yaml, install prometeus and control the parameters online - this is the only way to get more data and find which block is problematic.
But in 99% of cases, memory and buffering are always to blame, there is too little of it for all functions.

**Comment by skilurius** [comment]
Related https://github.com/OpenIPC/majestic/issues/171
