### ISSUE TITLE
nightMode not toggling or reading gpios on hi3518ev100

### ISSUE THREAD

**Issue by zerog2k** [OpenIPC/majestic#140]
# Required information

 * Camera board id: hi3518ev100
 * OpenIPC version: 2.3.11.08
 * Commit:
 * Branch:
 * Tag:
 * installation method: (by manual https://github.com/OpenIPC/openipc-2.1/wiki/install_hisi or another)
 * modified majestic.yaml: yes
 * cat /dev/kmsg
```
root@openipc-hi3518ev100:~# cat /dev/kmsg
cat: read error: Invalid argument
```

# Issue description

when attempting to use night mode controls with majestic, the gpio reading or toggling does not seem to occur until I run `ipctool gpio mux X` for each of the pins (sensor, cut filter pins, illuminator pins), while majestic is running e.g.
```
ipctool gpio mux 73
ipctool gpio mux 76
ipctool gpio mux 77
ipctool gpio mux 79
```
then toggling night mode again

at this point my suspicion is that there is some issue with gpio pinmux setup in majestic, or perhaps there is somethign else going on with the way hi3518ev100 pinmuxes are setup by default

# Information to attach

```
root@openipc-hi3518ev100:~# cat /etc/majestic.yaml 
system:
  webAdmin: enabled
  buffer: 2048
image:
  mirror: false
  flip: false
  rotate: none
  contrast: 50
  hue: 50
  saturation: 30
  luminance: 40
osd:
  enabled: false
  template: "%a %e %B %Y %H:%M:%S %Z"
  posX: 16
  posY: 16
nightMode:
  enabled: true
  nightAPI: true
  irSensorPin: 77
  backlightPin: 73
  irSensorPinInvert: false
  irCutPin1: 76
  irCutPin2: 79
  dncDelay: 5
records:
  enabled: false
  path: /mnt/mmcblk0p1/%F/%H.mp4
  maxUsage: 95
video0:
  enabled: true
  gopMode: normal
  rcMode: vbr
  bitrate: 1024
  fps: 15
video1:
  enabled: false
jpeg:
  enabled: true
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: false
  volume: auto
  srate: 8000
rtsp:
  enabled: true
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: false
  visualize: false
  debug: true
ipeye:
  enabled: false
watchdog:
  enabled: true
  timeout: 16
isp:
  blkCnt: 6
  lowDelay: false
  sensorConfig: /etc/sensors/ov9712_i2c_dc_720p.ini
  slowShutter: low
  antiFlicker: disabled
  memMode: reduction
  rawMode: slow
onvif:
  enabled: true
```

**Comment by zerog2k** [comment]
ok after a bit more experimentation, this is certainly a pinmux'ing issues
when majestic starts, and I'm assuming it opens gpio ports, the pinmuxing is reset to 0 for the pins, which is wrong (at least for hi3518ev100) for gpio. Per datasheet, these should be set to 1 to use gpio function of these pins.

```
root@openipc-hi3518ev100:~# #GPIO9_1, GPIO73
root@openipc-hi3518ev100:~# devmem 0x200F00CC
0x00000000
root@openipc-hi3518ev100:~# #GPIO9_4, GPIO76 
root@openipc-hi3518ev100:~# devmem 0x200F00D8
0x00000000
root@openipc-hi3518ev100:~# #GPIO9_5, GPIO77
root@openipc-hi3518ev100:~# devmem 0x200F00DC
0x00000000
root@openipc-hi3518ev100:~# #GPIO9_7, GPIO79
root@openipc-hi3518ev100:~# devmem 0x200F00E4
0x00000000
```

Interestingly, after majestic is started, if I manually set the pinmuxes on these, it works. 
```
root@openipc-hi3518ev100:~# devmem 0x200F00CC 32 0x1
root@openipc-hi3518ev100:~# devmem 0x200F00D8 32 0x1
root@openipc-hi3518ev100:~# devmem 0x200F00DC 32 0x1
root@openipc-hi3518ev100:~# devmem 0x200F00E4 32 0x1
```
But when majestic is restarted, the pinmuxes are reset to 0 (non-working).

I'm not sure what the convention is for these - if the pinmuxing is supposed to be set as a default on the OS, or if this is something the application (majestic) is supposed to do when opening gpio ports (but I have no idea how majestic is interacting with gpios, e.g. sysfs, devmem, syscalls, etc)
also unfortunately, these hi3518ev100/hi3516cv100 are stuck on a very ancient kernel (3.0.8), so not sure how much this might be related to why this isnt working

**Comment by zerog2k** [comment]
also possibly interesting
with majestic running a fresh config with no nightMode pins defined:

ipctool reginfo:
```
...
muxctrl_reg50 0x200f00c8 0x1 reserved [GPIO9_0]
muxctrl_reg51 0x200f00cc 0x1 reserved [GPIO9_1]
muxctrl_reg52 0x200f00d0 0x1 reserved [GPIO9_2]
muxctrl_reg53 0x200f00d4 0x1 reserved [GPIO9_3]
muxctrl_reg54 0x200f00d8 0x1 reserved [GPIO9_4]
muxctrl_reg55 0x200f00dc 0x1 reserved [GPIO9_5]
muxctrl_reg56 0x200f00e0 0x1 reserved [GPIO9_6]
muxctrl_reg57 0x200f00e4 0x1 reserved [GPIO9_7]
...
```

after setting majestic settings:
```
.nightMode.irSensorPin: 77
.nightMode.irCutPin1: 76
.nightMode.irCutPin2: 79
.nightMode.backlightPin: 73
```
when majestic restarts, output of ipctool reginfo:
```
muxctrl_reg50 0x200f00c8 0x1 reserved [GPIO9_0]
muxctrl_reg51 0x200f00cc 0x1 reserved [GPIO9_1]
muxctrl_reg52 0x200f00d0 0x1 reserved [GPIO9_2]
muxctrl_reg53 0x200f00d4 0x1 reserved [GPIO9_3]
muxctrl_reg54 0x200f00d8 0 [reserved] GPIO9_4
muxctrl_reg55 0x200f00dc 0x1 reserved [GPIO9_5]
muxctrl_reg56 0x200f00e0 0x1 reserved [GPIO9_6]
muxctrl_reg57 0x200f00e4 0 [reserved] GPIO9_7
```

it seems that something about the way majestic opens/configures the gpios/regs is causing the pinmux to get reset for the `irCutPin1` & `irCutPin2` pins

furthermore, enabling nightMode and night mode api, and then calling nightmode on also changes the pinmux registers in this way
```
muxctrl_reg50 0x200f00c8 0x1 reserved [GPIO9_0]
muxctrl_reg51 0x200f00cc 0 [reserved] GPIO9_1
muxctrl_reg52 0x200f00d0 0x1 reserved [GPIO9_2]
muxctrl_reg53 0x200f00d4 0x1 reserved [GPIO9_3]
muxctrl_reg54 0x200f00d8 0 [reserved] GPIO9_4
muxctrl_reg55 0x200f00dc 0 [reserved] GPIO9_5
muxctrl_reg56 0x200f00e0 0x1 reserved [GPIO9_6]
muxctrl_reg57 0x200f00e4 0 [reserved] GPIO9_7
```

**Comment by zerog2k** [comment]
ok after a bit of exploration into the majestic binary w/ cutter, I can see that there is some function which sets up the pin mux according to some configuration table in the code. (set_mux_reg, mux_gpio, ?).
If I patch the table for my muxctrl register addresses it works.

So I'm sure that this has to do with some hardcoded pinmux table in majestic codebase.
At least for hi3518 it seems like all the GPIO9_0 through GPIO9_7 should certainly have a pinmux value of 1, selecting the alternate "gpio" pin function, rather than the primary "nand flash data pins" function.

**Comment by flyrouter** [comment]
Thanks for your research, it looks impressive. 
We will try to fix the issue soon and give you the information for testing. 
In any case, we are very happy to have you with us.

**Comment by zerog2k** [comment]
looks like this has been resolved on recent builds of majestic master branch

**Comment by flyrouter** [comment]
Done
