### ISSUE TITLE
Packet rate is unaffected by CBR bitrate and spikes beyond link bandwidth

### ISSUE THREAD

**Issue by WizzardDr** [OpenIPC/majestic#141]
-  Camera board id: HiSilicon HI3516EV300 + IMX335
-  OpenIPC version: openipc.hi3516ev300-nor-fpv
-  Commit: https://github.com/OpenIPC/firmware/releases/tag/latest   (8 November 2023)
-  Branch: master
-  Tag: latest
-  installation method: copied from SD Card (sysupgrade --kernel=/tmp/uImage.hi3516ev300 --roo)
-  modified majestic.yaml: yes

```

video0:
  enabled: true
  fps:30
  bitrate:3000
  codec: h265
  rcMode: cbr
  gopSize: 0.2

```
```

outgoing:
  naluSize:1400

```

I was attempting to reduce packet rate to prevent glitching due to the link's bandwidth limit.

Lowering the bitrate doesn't affect the packet rate. When the camera is moved the packet rate increases and when the camera is put in the dark to increase noise the packet rate spikes and wifbroadcast reports lots of `UDP rxq overflow: 5 packets dropped`.

To test ` /usr/bin/majestic -s` was started:

At (2592x1520@30)
The link fluctuates around ~350pkt/s with this in the console:
![image](https://github.com/OpenIPC/majestic/assets/93602460/97b372dd-e469-4910-a129-0c5505703828)
When the camera is covered the link spikes to ~1050pkt/s with this in the console:
![image](https://github.com/OpenIPC/majestic/assets/93602460/dd4244a2-861a-4126-9592-cc08235da9d7)

At 720p Crop (1280x720@30)
The link fluctuates around ~400pkt/s with nothing extra in the console.
When the camera is covered the link spikes to ~960pkt/s with nothing extra in the console.

I expect CBR should maintain a constant packet rate dependent on bitrate and naluSize.

# Steps to reproduce

Setup HI3516EV300 + IMX335 and AR9271 running openipc.hi3516ev300-nor-fpv
Setup ubuntu with wfb-ng and gst-launch-1.0
Run the system with majestic.yaml modified with the parameters above.
Inspect wfb-cli gs packet rate.

# Information to attach
Additionally majestic outputs `MinIQp set 32 error for out of [0 30]`, where is `MinIQp` defined?

`/usr/bin/majestic -s`
![image](https://github.com/OpenIPC/majestic/assets/93602460/fb8e26b1-bbfb-4eee-bdd9-b5ad22f96701)

`cat /etc/majestic.yaml`
![image](https://github.com/OpenIPC/majestic/assets/93602460/0445633a-3493-4be7-9404-bef71a7f307c)

**Comment by WizzardDr** [comment]
~Adding `IPQPDelta: -8` in majestic.yaml under `isp:` has distributed the bitrate away from the I frames and dramatically reduced the spikes.~

**Comment by widgetii** [comment]
Firstly, try to get rid of VB fail messages in log by gradually increasing memory buffers in `blkCnt`:

![image](https://github.com/OpenIPC/majestic/assets/6576495/ed5944ff-f328-4ec7-b9e4-274143e34c2f)

It has huge impact on overall system performance

**Comment by WizzardDr** [comment]
`blkCnt: 7`
![image](https://github.com/OpenIPC/majestic/assets/93602460/fa4b42ae-166f-458f-b42c-468132201c0f)

`blkCnt: 8`
No image is transmitted
![image](https://github.com/OpenIPC/majestic/assets/93602460/f427753f-247e-4eb2-88b4-df1b2f96b31a)

**Comment by widgetii** [comment]
Can you stay with `blkCnt: 7` and test it with `fps: 20`, `25`? I guess the issue is SoC is not capable to do all this video pipeline in real-time so it drops frames

**Comment by WizzardDr** [comment]
You are correct, I reduced the fps to 25 which it got rid of the VB fail message. Also I think I was wrong, as it now seams `IPQPDelta: -8` has no effect. What can I do now?

**Comment by yang151-bit** [comment]
![openipc_minIQp](https://github.com/OpenIPC/majestic/assets/61414874/0082586b-ddfa-433a-ad1e-52a1d2897ba4)
I have the same problem of `MinIQp set 32 error for out of [0 30]`. And the lost in wfb-cli gs is very high.
![wfb-cli_gs_highLost](https://github.com/OpenIPC/majestic/assets/61414874/4dfb3448-c072-454a-ba12-4595f074fbae)

**Comment by widgetii** [comment]
Obviously, '32' is not in '0..30' range as error message suggested

**Comment by flyrouter** [comment]
Done
