### ISSUE TITLE
Recording always in fast motion

### ISSUE THREAD

**Issue by spirifer** [OpenIPC/majestic#144]
# Required information

 * Camera board id: ssc338Q +NVR
 * OpenIPC version: fpv
 * Commit:
 * Branch:
 * Tag:
 * installation method: (by manual https://github.com/OpenIPC/openipc-2.1/wiki/install_hisi or another)
 * modified majestic.yaml: yes
 * killall majestic
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
   Core dump file from /tmp/ , e.g. /tmp/majestic.806.11.1619707881.core

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.
Hello guys, yesterday I was testing the settings available on majestic.full on the ssc338Q and managed to get a good image, even in low light, so good to the point that I decided to quickly install the camera on the drone, but first I tested the recording with the NVR , the result was strange and surprising, the recording was always in fast motion, but with the 7205v200 everything was fine, so it wasn't the NVR. After several attempts to restore the recording speed, which included sysupgrade, it returned to normal recording speed, but with a darker image, which I don't like, then I changed the parameters in majestic.yaml and it returned to fast motion recording,
Through the process of elimination I concluded that the problem is in the "ISP:, "exposure: xx" section, 10 by default but when I increase it, the recording speed also increases, and with a value of 30 fast motion is already noticeable.
Has anyone ever encountered this problem?

# Expectations

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant log output (`logread -f`)
 - [ ] majestic.yaml configuration (`cat /etc/majestic.yaml`)system:
  webAdmin: enabled
  buffer: 1024
image:
  mirror: false
  flip: false
  rotate: none
  contrast: 70
  hue: 50
  saturation: 50
  luminance: 50
osd:
  enabled: false
  template: "%a %e %B %Y %H:%M:%S %Z"
nightMode:
  enabled: false
records:
  enabled: false
  path: /mnt/mmcblk0p1/%F/%H.mp4
  maxUsage: 95
video0:
  
  enabled: true
  bitrate: 12288
  codec: h265
  rcMode: cbr
  gopSize: 1.5
  size: 1280x720
  fps: 60
  
video1:
  enabled: false
jpeg:
  enabled: false
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: false
  volume: auto
  srate: 8000
rtsp:
  enabled: true
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: false
  visualize: false
  debug: false
ipeye:
  enabled: false
watchdog:
  enabled: true
  timeout: 10
isp:

  exposure: 60
  drc: 350
  IPQPDelta: -8
  
outgoing:
  enabled: true
  server: udp://127.0.0.1:5600

**Comment by flyrouter** [comment]
Done
