### ISSUE TITLE
Video bitrate setting stuck to 4096 on first start, loaded correctly after reload config

### ISSUE THREAD

**Issue by tipoman9** [OpenIPC/majestic#151]
* Camera board id: hi3516ev300
 * OpenIPC version:  Majestic Fpv for HiSilicon, version master+bb1923f, built on 2023-12-07
 
# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

Set 
```
video0:
  bitrate: 8000
```
 in majestic.yaml to any value different from 4096
Start majestic. Notice the bitrate in the log or in the video player
Start from another session `killall -1 majestic`
The bitrate will be changed to the value from majestic.yaml

![majestic_not_loading_bitrate](https://github.com/OpenIPC/majestic/assets/97629810/d310c95a-9b5f-48b1-a298-030a247a9b82)

The problem does not appear on SigmaStart boards

**Comment by skilurius** [comment]
I had the same issue on my Goke board before, but it seems to work fine now.
Have you tested this on a more recent version?

**Comment by tipoman9** [comment]
Yes, tested today in hi3516ev300 board with recent majestic, the problem does not appear.
