### ISSUE TITLE
Segfault when streaming from h264 endpoint

### ISSUE THREAD

**Issue by NekoB0x** [OpenIPC/majestic#159]
# Required information

 * Camera board id: hi3518ev100
 * OpenIPC version: 2.4.03.11-lite
 * Commit: d8f8854
 * Branch: master
 * Tag: latest
 * installation method: (by manual https://github.com/OpenIPC/openipc-2.1/wiki/install_hisi or another)
 * modified majestic.yaml: yes

# Issue description

Majestic segfaults when streaming from any h264 endpoint (RTSP stream0/1, HLS, /video.mp4), randomly between 10 minutes and ~8 hours.
Doesn't segfault with mjpeg or when idle.

After segfault /proc/umap/h264e PICTURE INFO shows increasing BufLeak.
OpenIPC has CHN ATTR BufSize set to 691200, on stock firmware it's set to 1382400 so it could be related.

This issue could be related to #139.

# Expectations

No segfault.

# Steps to reproduce

 1. Start streaming from RTSP/HLS/video.mp4
 2. Wait up to 8 hours

# Information to attach

[coredump.tgz.txt (rename to .tgz)](https://github.com/OpenIPC/majestic/files/14584643/coredump.tgz.txt)

**Comment by zerog2k** [comment]
@NekoB0x looks like recent builds have been updated with increased buffer size which match oem buffer sizes, as discussed in #171 
However, myself and others are still experiencing crashing. Maybe you want to try a recent build and see if this improves your situation?

**Comment by NekoB0x** [comment]
@zerog2k Tested 2.4.08.26-lite, same crash after 4 hours.

**Comment by skilurius** [comment]
Related https://github.com/OpenIPC/majestic/issues/171
