### ISSUE TITLE
RTMP reconnection and timeout settings

### ISSUE THREAD

**Issue by noniepark** [OpenIPC/majestic#160]
Hi

I would like to configure number of reconnect attempt and reconnect timeout for RTMP protocol.
By default, maximum number of RTMP reconnection is 200 and timeout is 5 seconds.
So when the network was down or my service on the server is unavailable for a moment and it gave up to reconnect.
Since there's no description or guide for these parameter modification in majestic.full or majestic.yaml.
Is there a way to change these numbers? Would be nice if number of attempt can set to infinity.

Thank you.

**Comment by skilurius** [comment]
This was addressed on the current build, the new logic works as follows:
```
    0-200 tries = 10 seconds timeout
  200-500 tries = 60 seconds timeout
 500-1000 tries = 300 seconds timeout
    1000+ tries = 600 seconds timeout
```

It was initially intended not to reconnect indefinitely to avoid ddos on unmaintained devices, but if one request is done every 10 minutes it should not cause any problems.

**Comment by noniepark** [comment]
Thank you for your suggestion.
