### ISSUE TITLE
gk7205v300 + imx 355 - image issue "Autoadjust image param scAttrContrField"

### ISSUE THREAD

**Issue by flyzet-prog** [OpenIPC/majestic#163]
Hello dear developers i am expiried some issues with my image settings, IQ profile along with sensor configuration set properly. Let's say i set some parameters in image tab section of Majestic , contrast, illuminance, hue, etc. After some random time it makes auto adjustments of my previous image parameters and override it. Please let me know how to resolve this if some one expired the same issues. Please see attachments.
GK7205 + IMX335
OPENIPC_VERSION=2.4.04.17
GITHUB_VERSION="master+ff27178, 2024-04-17"
BUILD_OPTION=lite
<img width="659" alt="Screenshot 2024-04-19 at 14 44 28" src="https://github.com/OpenIPC/majestic/assets/73076482/2fb38bde-b613-48c9-9671-d181c35ae6a0">
<img width="684" alt="Screenshot 2024-04-19 at 14 50 18" src="https://github.com/OpenIPC/majestic/assets/73076482/ebb16c6b-9806-4a4e-a3bc-bd20c4ffd305">

**Comment by skilurius** [comment]
A setting will be added to deactivate image tuning on the next build.

**Comment by flyzet-prog** [comment]
> A setting will be added to deactivate image tuning on the next build.

Thank you, waiting for the next build.

**Comment by skilurius** [comment]
I assume this should have been fixed, if there is still an issue please respond to this ticket.
