### ISSUE TITLE
Why is the recorded video overwritten?

### ISSUE THREAD

**Issue by suiaiyun** [OpenIPC/majestic#164]
May I ask how to avoid videos recorded at the same time being overwritten when setting up Majestic to record video files? For example, there is a file 2024-05-12/10-03-mp4. When my board is powered off and restarted, the time will come back to 2024-05-12/10-03, which will default to overwriting the previous 2024-05-12/10-03-mp4. How can I avoid this situation?

**Comment by skilurius** [comment]
By default the file is not overwritten but the recording is appended to the existing file.
