### ISSUE TITLE
Support /dev/sar_adc_drv on GrainMedia platform

### ISSUE THREAD

**Issue by willersonsp** [OpenIPC/majestic#172]
# Required information

 * Camera board id: GrainMedia 813X series
 * OpenIPC version: Latest one
 * Commit: Latest one
 * Branch: master
 * Tag: master
 * installation method: Manual
 * modified majestic.yaml: yes - disabled Watchdog: causes crash on GM platform

# Issue description

Add support for GrainMedia /dev/sar_adc_drv device to read analogic levels, on my board, it is that controls the InfraRed sensor.

@wberube added support on divinus with some of my help.

https://github.com/OpenIPC/divinus/commit/959dadd11bc5ab9ea734759cdd712a88b1102b3f

If some need help on testing, just ask i will be gladly to help.

**Comment by skilurius** [comment]
Hello, the grainmedia adc device has been added to nightmode for testing, please try the following parameters:
```
cli -s .nightMode.lightMonitor true
cli -s .nightMode.adcReadout true
cli -s .nightMode.minThreshold 64
cli -s .nightMode.maxThreshold 128
```

**Comment by willersonsp** [comment]
@skilurius tested here, sometimes it got stuck to max reading for quite some time and it didnt activate the IRCut gpio when threshold is met.

---Edit
it was configured with your values, setting

cli -s .nightMode.minThreshold 64 -> 1
cli -s .nightMode.maxThreshold 128 -> 124 (max value reading here )

worked nicely,

thanks for the hard work.
