### ISSUE TITLE
OSD not shown on substream (video1)

### ISSUE THREAD

**Issue by zerog2k** [OpenIPC/majestic#175]
Hardware
Processor: hi3518ev100
Family: hi3516cv100
Sensor: ov9712_i2c
Flash: 8 MB

Firmware 
Version: 2.4.08.09-lite
Build: local+build, 2024-08-09
Majestic: master+d3f2c7a, 2024-08-08
U-Boot: U-Boot 2010.06-dirty (Nov 17 2023 - 09:38:06)

# Issue description

OSD not seen on sub-stream (video1), only seen on main-stream (video0)

# Expectations

OSD seen also on sub-stream (video1).

# Information to attach

majestic.yaml:
```
system:
  webPort: 80
  httpsPort: 443
  logLevel: debug
  buffer: 1024
  plugins: false
isp:
  antiFlicker: disabled
  blkCnt: 6
  dis: false
image:
  mirror: false
  flip: false
  rotate: 0
  contrast: 50
  hue: 50
  saturation: 50
  luminance: 50
video0:
  enabled: true
  codec: h264
  fps: 15
  bitrate: 1024
  rcMode: vbr
  gopSize: 1.0
  gopMode: normal
  size: 1280x720
  sliceUnits: 0
video1:
  enabled: true
  codec: h264
  size: 640x360
  fps: 10
  bitrate: 512
  gopMode: normal
  rcMode: vbr
  sliceUnits: 0
  gopSize: 1.0
jpeg:
  enabled: true
  qfactor: 25
  fps: 5
osd:
  enabled: true
  font: "/usr/share/fonts/truetype/UbuntuMono-Regular.ttf"
  template: "%F %T"
  posX: 16
  posY: 16
audio:
  enabled: false
  volume: 30
  srate: 8000
  codec: opus
  outputEnabled: false
  outputVolume: 30
rtsp:
  enabled: true
  port: 554
nightMode:
  colorToGray: true
  irCutSingleInvert: false
  lightMonitor: true
  lightSensorInvert: false
  backlightPin: 73
  irCutPin1: 76
  irCutPin2: 79
  lightSensorPin: 77
  monitorDelay: 0
motionDetect:
  enabled: true
  visualize: false
  debug: false
records:
  enabled: false
  path: "/mnt/mmcblk0p1/%F/%H.mp4"
  maxUsage: 95
outgoing:
  enabled: false
watchdog:
  enabled: true
  timeout: 60
hls:
  enabled: false
onvif:
  enabled: true
```

**Comment by skilurius** [comment]
Hello, it is generally intended to keep the substream free of the osd, so the stream can be processed by other software solutions.
The osd/text quality will also decrease immensely if the resolution is below 720p.

**Comment by zerog2k** [comment]
Ok that’s reasonable.

**Comment by PeakSense** [comment]
Hey,

is there a way of adding it anyways?

**Comment by barakus02** [comment]
is it possible to remove the osd that shows Fps, bitrate, and ms delay? I am working on a solution for video monitoring and just want a clean video output
