### ISSUE TITLE
Saturation control doesn't work properly for SSC378DE

### ISSUE THREAD

**Issue by iGraveD** [OpenIPC/majestic#181]
# Required information

 * Camera board id: SSC378DE
 * OpenIPC version: 2.4.09.05-lite
 * installation method: default OpenIPC

# Issue description

Saturation seem not to change significantly for the most of the colors when changing the saturation value. The picture below contains two examples. Example 1 (left) is 'saturation' set to 1 and 100 for SSC378DE, Example 2 (screenshot right, expected behaviour) is the same saturation values set with a different camera board type.

![saturation](https://github.com/user-attachments/assets/e104ac7c-f441-4d71-89c9-11fb960f6b4b)

# Expectations

Changing saturation should reflect colors at the screen, saturation value '1' should make the picture black and white, saturation 100 should make the picture oversaturated.

# Steps to reproduce

 1. Open Majestic Settings.
 2. At Image section, drag Saturation either to 1 or 100.
 3. Save and restart Majestic.

# Information to attach

 - [ ] Any relevant log output (`logread -f`)
 - [ ] majestic.yaml configuration (`cat /etc/majestic.yaml`)

**Comment by skilurius** [comment]
Please test the newest build.

**Comment by iGraveD** [comment]
> Please test the newest build.

I've just tested this with firmware version 2.4.09.06-lite, and the issue still seems to persist.

**Version** 2.4.09.06-lite
**Build** master+88d3b14, 2024-09-06
**Majestic** master+439992d, 2024-09-02

**Comment by skilurius** [comment]
[infinity6c.lite.master.tar.bz2](https://openipc.s3-eu-west-1.amazonaws.com/majestic.infinity6c.lite.master.tar.bz2)

**Comment by iGraveD** [comment]
> [infinity6c.lite.master.tar.bz2](https://openipc.s3-eu-west-1.amazonaws.com/majestic.infinity6c.lite.master.tar.bz2)

Thanks, it worked! :)
