### ISSUE TITLE
Mismatch in Minimum Value for Microphone Sensitivity Between Majestic Web Interface and Parser

### ISSUE THREAD

**Issue by iGraveD** [OpenIPC/majestic#182]
# Required information

 * Processor: t31x, ssc378de
 * OpenIPC version:  2.4.09.05-lite

# Issue description

The Majestic web interface allows setting the microphone volume to 0. However, an error occurs when Majestic reads this configuration, suggesting a discrepancy between the web interface's allowed minimum value and the parser's expected range.

# Expectations

No error should occur when the microphone sensitivity is set to 0, or the web interface should enforce a minimum value that aligns with the parser's expectations.

# Steps to reproduce

1. Go to Majestic > Settings > Audio.
2. Drag the Microphone Volume slider to zero.
3. Save the changes.
4. Restart Majestic.
5. Navigate to Information > Majestic.

At this point, you will encounter the following error:

```majestic[624]: Can't parse param 'volume' value '0'. Value '0' is not in the range [1; 100].```

**Comment by skilurius** [comment]
Please test the newest build.

**Comment by iGraveD** [comment]
> Please test the newest build.

I've just tested this with firmware version 2.4.09.06-lite, and the issue still seems to persist.

**Version** 2.4.09.06-lite
**Build** master+88d3b14, 2024-09-06
**Majestic** master+439992d, 2024-09-02

**Comment by skilurius** [comment]
https://openipc.s3-eu-west-1.amazonaws.com/majestic.t31.lite.master.tar.bz2

**Comment by iGraveD** [comment]
> https://openipc.s3-eu-west-1.amazonaws.com/majestic.t31.lite.master.tar.bz2

Thanks, it worked! :)
