### ISSUE TITLE
RTMP push from Majestic to nginx RTMP module: size 0x0, fps 0, connection interrupts after some time

### ISSUE THREAD

**Issue by iGraveD** [OpenIPC/majestic#193]
# Required information

 * SoC: ssc378de
 * OpenIPC version: 2.4.09.08-lite
 * Build: master+88d3b14, 2024-09-08
 * Majestic: master+304fbae, 2024-09-06
 * installation method: Firmware > Update > Install update from GitHub

# Issue description

I am not sure, if these issues are really related to each other, but I will report them together:

### Unable to set the microphone value to 0db

I set the "Microphone volume" option to 0.

However, Majestic log says:
```
majestic[624]: Input: 8kHz, 10dB
```

Expected: `Input: 8kHz, 0%, 0dB`, like in other cameras running OpenIPC.
Note: with percentage value. I expected Majestic output to have exactly the same format on all cameras, where possible.

### Noises instead of sound

I hear strange noises in YouTube broadcast:
https://www.youtube.com/embed/EscQu5-wRS0

Even if I set the “Microphone Volume” setting to 100, I don't hear any real sounds from the camera microphone, only noises getting louder.

### Log entries

In Majestic log, entries appear once every 4-40 minutes, on average once every 10 minutes:

```
majestic[624]: ^[[1;33m[MI WRN ]: MI_AI_Read[1121]: 
majestic[624]: MI AI device 0 ChnGrp 0 Buffer(s) is lost due to slow fetching.
majestic[624]: ^[[0m
majestic[624]: ^[[1;33m[MI WRN ]: MI_AI_Read[1122]: 
majestic[624]: Current buf index[2259], recording buf index[2258].
majestic[624]: ^[[0m
```

### What I have already checked

All the connectors on the board seem properly connected.
I replaced the the power supply with a different one – no changes.
Audio steam has the same noises: http://usachov.eu:20055/audio.m4a.

The average CPU load:
```
09:33:26 up 21 min,  load average: 15.54, 15.45, 12.17
```

Top processes: 
```
root@openipc-ssc378de:/tmp# top
Mem: 27216K used, 26644K free, 0K shrd, 0K buff, 9484K cached
CPU:   0% usr  20% sys   0% nic  80% idle   0% io   0% irq   0% sirq
Load average: 15.72 13.63 7.44 1/61 1745
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
  624     1 root     S    30676  57%   7% majestic -s
 1743  1734 root     R     1332   2%   7% top
 2917     2 root     DW       0   0%   7% [isp0_P0_MAIN]
  450     1 root     S     1384   3%   0% syslogd -n -C64 -t
 1734   624 root     S     1328   2%   0% {run.cgi} /bin/sh /var/www/cgi-bin/j/r
    1     0 root     S     1320   2%   0% init
  454     1 root     S     1320   2%   0% /sbin/klogd -n
  522     1 root     S     1320   2%   0% ntpd -n
  517     1 root     S     1320   2%   0% udhcpc -x hostname:openipc-ssc378de -A
  532     1 root     S     1320   2%   0% crond -f -c /etc/crontabs
  631     1 root     S     1320   2%   0% /sbin/getty -L console 0 vt100
 1745     1 root     S     1320   2%   0% timeout 3 top
  529     1 root     S      848   2%   0% dropbear -R -B -k -p 22 -K 300
  568     2 root     DW       0   0%   0% [IspDriverThread]
 2921     2 root     DW       0   0%   0% [venc0_P0_MAIN]
  345     2 root     IW       0   0%   0% [kworker/0:2-eve]
 2912     2 root     DW       0   0%   0% [vif0_P0_MAIN]
 2924     2 root     DW       0   0%   0% [ai0_P0_MAIN]
  264     2 root     IW<      0   0%   0% [kworker/0:1H-kb]
 2922     2 root     DW       0   0%   0% [venc8_P0_MAIN]
Terminated
root@openipc-ssc378de:/tmp# 
```

**Comment by skilurius** [comment]
Duplicate https://github.com/OpenIPC/majestic/issues/191

**Comment by skilurius** [comment]
Wrong title, duplicate https://github.com/OpenIPC/majestic/issues/191
