### ISSUE TITLE
Sound is no longer working

### ISSUE THREAD

**Issue by tipoman9** [OpenIPC/majestic#196]
* Camera board id: SigmaStar ssc338q and ssc30kq
 * OpenIPC version: Majestic Lite for SigmaStar, version master+569441d, built on 2024-09-08

# Issue description
When sound is enabled, errors appear in majestic log and no sound is embedded into the video.

```
audio:
  enabled: true
  srate: 8000
```

![image_2024-09-09_20-34-58](https://github.com/user-attachments/assets/ee07f586-262b-4e08-ad38-1b1888d14039)

dmesg output attached.
[dmesg.txt](https://github.com/user-attachments/files/16935054/dmesg.txt)

Sound was working with majestic versions from April 2024, and stopped when firmware update was applied.

**Comment by skilurius** [comment]
Please test the current build: [infinity6e.lite.tar](https://openipc.s3-eu-west-1.amazonaws.com/majestic.infinity6e.lite.master.tar.bz2)

**Comment by tipoman9** [comment]
> Please test the current build: [infinity6e.lite.tar](https://openipc.s3-eu-west-1.amazonaws.com/majestic.infinity6e.lite.master.tar.bz2)

This file seems to work, or at least it does not give an error. No microphone on the desk to test it right now.

**Comment by skilurius** [comment]
I assume this should have been fixed, if there is still an issue please respond to this ticket.

**Comment by tipoman9** [comment]
The issue is still not fixed, there is no sound embedded in the video.
Compared majestic log with a working version and 
```
[   audio] mi_ai_init@273      
[   audio] mi_ao_init@188  
```
records missing.
![image](https://github.com/user-attachments/assets/b641c64f-3b69-4661-b5be-d5a1e5f82430)

I'm comparing with a version with sound of majestic 
`Majestic Lite for SigmaStar, version master+eecb684, built on 2024-04-28`

**Comment by tipoman9** [comment]
Downloaded older version of majestic
Majestic Lite for SigmaStar, version master+eecb684, built on 2024-04-28
copied it over the latest firmware, copied also /usr/lib/libmi_sed.so
And I have sound.
So there is definitely some issue with the latest release.

**Comment by skilurius** [comment]
Please provide full output logs.

Test with current build:
```
19:25:14  <       majestic> [    main] main@237                      Majestic Lite for SigmaStar, version master+78fb2a3, built on 2024-09-09
19:25:14  <       majestic> [app_conf] parse_app_config@396          Main audio codec is opus (other options: aac, pcm, alaw, ulaw)
19:25:14  <       majestic> [watchdog] watchdog_start@94             Detected infinity Watchdog
[...]
19:25:14  <       majestic> [   audio] mi_ai_init@273                Input: chn0, 48kHz, 6dB
[...]
19:25:14  <       majestic> [   audio] mi_ao_init@188                Output: 48kHz, -32dB
[...]
```

**Comment by tipoman9** [comment]
Did sysupgrade -r and downloaded Majestic Lite for SigmaStar, version master+78fb2a3, built on 2024-09-09
Confirm sound now works on ssc338q
