### ISSUE TITLE
/image.jpg fails after ~24h of work

### ISSUE THREAD

**Issue by mariarti** [OpenIPC/majestic#25]
* Camera board id: IVG85HG50PYA-S (16ev300)
 * OpenIPC version: Free, master+6fbbadd, 2021-10-08
Issue: Approximately after a 24 hours of work, the screenshots by url `/image.jpg` are stopped.
Screenshots are seted up on narodmon.ru with an interval of 15 minutes.
Same with `wget`
```
$ wget  192.168.1.172:8888/image.jpg
--2021-10-12 09:59:14--  http://192.168.1.172:8888/image.jpg
Connecting to 192.168.1.172:8888... connected.
HTTP request sent, awaiting response...
```
```
15:13:16 [  evhttp] incoming_req@110              on request send /image.jpg for 192.168.1.160
15:13:16 [  evhttp] on_jpeg_data_cb@435           Taking JPEG is in progress, returning from on_jpeg_data_cb
```
At the same time, it is observed that this problem occurs when netip: snapshots: true
`15:13:19 [   netip] on_jpeg_data_cb@1699          Empty JPEG snapshot has been received from encoder, skipping it`

However, if you turn it off, then everything works as it should be.
A series of 3 tests was performed, reproduced with 100% success. 

Dmitry supposed:
`The NVR is also requested not a full-sized JPEG, but something D1, so arrival two different requests at the same time`

**Comment by mariarti** [comment]
Another one hundred percent case.
Netip and ONVIF are turned off.
The rest of the configuration is default.
```
500 Internal Server Error
Internal error
```
```
14:26:12 [  evhttp] incoming_req@111              on request send /image.jpg for 1.2.3.4
14:26:12 [     sdk] sdk_take_jpeg@2123            Stuck in progress
14:26:12 [  evhttp] on_jpeg_data_cb@437           Empty data has been returned for JPEG request
14:26:12 [  evhttp] incoming_req@111              on request send /favicon.ico for 1.2.3.4
14:26:12 [  static] send_file_to_user@91          Web static mode is disabled
```

**Comment by widgetii** [comment]
Sorry for the long time waiting, it took much time to resolve it.

JPEG snapshot code block was refactored, for HiSi devices internal queue was added and after some tests it might be expanded to support on other platforms

**Comment by FlyRouter** [comment]
Thank you, Sir !
