### ISSUE TITLE
некорректная запись

### ISSUE THREAD

**Issue by zWolf-SW** [OpenIPC/majestic#27]
# Required information

 * Camera board id: hi3516ev300
 * OpenIPC version: 2.1
 * Commit:  Majestic Free for HiSilicon, version master+6fbbadd, built on 2021-10-08

 * Branch:
 * Tag:
 * installation method: (by manual https://github.com/OpenIPC/openipc-2.1/wiki/install_hisi or another)
 * modified majestic.yaml: yes
 * .........
 * records:
  enabled: true
  path: /mnt/mmc/records/%Y/%m/%d/%H.mp4

  # in %
  maxUsage: 95

video0:
  enabled: true
  codec: h264
 * .........
 * cat /dev/kmsg
 * 6,0,0,-;Booting Linux on physical CPU 0x0
5,1,0,-;Linux version 4.9.37 (swit@zWolf) (gcc version 7.5.0 (Buildroot -g9f51889-dirty) ) #1 Wed Oct 13 17:45:02 MSK 2021
6,2,0,-;CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c53c7d
6,3,0,-;CPU: div instructions available: patching division code
6,4,0,-;CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
6,5,0,-;OF: fdt:Machine model: Hisilicon HI3516EV300 DEMO Board
6,6,0,-;cma: Reserved 96 MiB at 0x42000000
6,7,0,-;Memory policy: Data cache writeback
7,8,0,-;On node 0 totalpages: 32768
7,9,0,-;free_area_init_node: node 0, pgdat c04dfcac, node_mem_map c1eca000
7,10,0,-;  Normal zone: 256 pages used for memmap
7,11,0,-;  Normal zone: 0 pages reserved
7,12,0,-;  Normal zone: 32768 pages, LIFO batch:7
6,13,0,-;CPU: All CPU(s) started in SVC mode.
7,14,0,-;pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
7,15,0,-;pcpu-alloc: [0] 0
6,16,0,-;Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 32512
5,17,0,-;Kernel command line: mem=128M console=ttyAMA0,115200 panic=20 rootfstype=squashfs root=/dev/mtdblock3 init=/init mtdparts=hi_sfc:256k(boot),64k(env),2048k(kernel),5120k(rootfs),-(rootfs_data) mmz_allocator=cma mmz=anonymous,0,0x42000000,96M
6,18,0,-;PID hash table entries: 512 (order: -1, 2048 bytes)
6,19,0,-;Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
6,20,0,-;Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
6,21,0,-;Memory: 26176K/131072K available (3809K kernel code, 129K rwdata, 840K rodata, 176K init, 179K bss, 6592K reserved, 98304K cma-reserved)
5,22,0,-;Virtual kernel memory layout:\x0a    vector  : 0xffff0000 - 0xffff1000   (   4 kB)\x0a    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)\x0a    vmalloc : 0xc8800000 - 0xff800000   ( 880 MB)\x0a    lowmem  : 0xc0000000 - 0xc8000000   ( 128 MB)\x0a    modules : 0xbf000000 - 0xc0000000   (  16 MB)\x0a      .text : 0xc0008000 - 0xc03c0660   (3810 kB)\x0a      .init : 0xc0494000 - 0xc04c0000   ( 176 kB)\x0a      .data : 0xc04c0000 - 0xc04e04a0   ( 130 kB)\x0a       .bss : 0xc04e2000 - 0xc050eefc   ( 180 kB)
6,23,0,-;SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
6,24,0,-;NR_IRQS:16 nr_irqs:16 16
4,25,0,-;Gic dist init...
6,26,0,-;arm_arch_timer: Architected cp15 timer(s) running at 50.00MHz (phys).
6,27,0,-;clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0xb8812736b, max_idle_ns: 440795202655 ns
6,28,6,-;sched_clock: 56 bits at 50MHz, resolution 20ns, wraps every 4398046511100ns
6,29,14,-;Switching to timer-based delay loop, resolution 20ns
6,30,123,-;clocksource: arm,sp804: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 637086815595 ns
6,31,336,-;Console: colour dummy device 80x30
6,32,354,-;Calibrating delay loop (skipped), value calculated using timer frequency.. 100.00 BogoMIPS (lpj=500000)
6,33,364,-;pid_max: default: 32768 minimum: 301
6,34,441,-;Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
6,35,450,-;Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
6,36,889,-;CPU: Testing write buffer coherency: ok
6,37,1097,-;Setting up static identity map for 0x40008200 - 0x40008258
6,38,1911,-;devtmpfs: initialized
6,39,5436,-;VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
6,40,5656,-;clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
6,41,5675,-;futex hash table entries: 256 (order: -1, 3072 bytes)
6,42,8888,-;pinctrl core: initialized pinctrl subsystem
6,43,9222,-;NET: Registered protocol family 16
6,44,9521,-;DMA: preallocated 256 KiB pool for atomic coherent allocations
6,45,10650,-;Serial: AMBA PL011 UART driver
6,46,12109,-;12040000.uart: ttyAMA0 at MMIO 0x12040000 (irq = 20, base_baud = 0) is a PL011 rev2
6,47,280110,-;console [ttyAMA0] enabled
6,48,283191,-;12041000.uart: ttyAMA1 at MMIO 0x12041000 (irq = 21, base_baud = 0) is a PL011 rev2
6,49,312103,-;ssp-pl022 12070000.spi: ARM PL022 driver, device ID: 0x00800022
 SUBSYSTEM=amba
 DEVICE=+amba:12070000.spi
6,50,317790,-;ssp-pl022 12070000.spi: mapped registers from 0x12070000 to c886f000
 SUBSYSTEM=amba
 DEVICE=+amba:12070000.spi
6,51,324844,-;ssp-pl022 12071000.spi: ARM PL022 driver, device ID: 0x00800022
 SUBSYSTEM=amba
 DEVICE=+amba:12071000.spi
6,52,330541,-;ssp-pl022 12071000.spi: mapped registers from 0x12071000 to c8873000
 SUBSYSTEM=amba
 DEVICE=+amba:12071000.spi
6,53,338185,-;usbcore: registered new interface driver usbfs
6,54,342426,-;usbcore: registered new interface driver hub
6,55,346475,-;usbcore: registered new device driver usb
6,56,351115,-;clocksource: Switched to clocksource arch_sys_counter
6,57,377878,-;NET: Registered protocol family 2
6,58,381531,-;TCP established hash table entries: 1024 (order: 0, 4096 bytes)
6,59,387198,-;TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
6,60,392275,-;TCP: Hash tables configured (established 1024 bind 1024)
6,61,397372,-;UDP hash table entries: 256 (order: 0, 4096 bytes)
6,62,401919,-;UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
6,63,406990,-;NET: Registered protocol family 1
6,64,410772,-;RPC: Registered named UNIX socket transport module.
6,65,415419,-;RPC: Registered udp transport module.
6,66,418810,-;RPC: Registered tcp transport module.
6,67,422210,-;RPC: Registered tcp NFSv4.1 backchannel transport module.
6,68,428832,-;workingset: timestamp_bits=30 max_order=15 bucket_order=0
6,69,442255,-;squashfs: version 4.0 (2009/01/31) Phillip Lougher
6,70,450516,-;jffs2: version 2.2 (NAND) (ZLIB) (RTIME) (c) 2001-2006 Red Hat, Inc.
6,71,458985,-;Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
6,72,465109,-;io scheduler noop registered
6,73,467720,-;io scheduler deadline registered (default)
6,74,473603,-;pl061_gpio 120b0000.gpio_chip: PL061 GPIO chip @0x120b0000 registered
 SUBSYSTEM=amba
 DEVICE=+amba:120b0000.gpio_chip
6,75,480846,-;pl061_gpio 120b1000.gpio_chip: PL061 GPIO chip @0x120b1000 registered
 SUBSYSTEM=amba
 DEVICE=+amba:120b1000.gpio_chip
6,76,488157,-;pl061_gpio 120b2000.gpio_chip: PL061 GPIO chip @0x120b2000 registered
 SUBSYSTEM=amba
 DEVICE=+amba:120b2000.gpio_chip
6,77,495426,-;pl061_gpio 120b3000.gpio_chip: PL061 GPIO chip @0x120b3000 registered
 SUBSYSTEM=amba
 DEVICE=+amba:120b3000.gpio_chip
6,78,502705,-;pl061_gpio 120b4000.gpio_chip: PL061 GPIO chip @0x120b4000 registered
 SUBSYSTEM=amba
 DEVICE=+amba:120b4000.gpio_chip
6,79,509952,-;pl061_gpio 120b5000.gpio_chip: PL061 GPIO chip @0x120b5000 registered
 SUBSYSTEM=amba
 DEVICE=+amba:120b5000.gpio_chip
6,80,517242,-;pl061_gpio 120b6000.gpio_chip: PL061 GPIO chip @0x120b6000 registered
 SUBSYSTEM=amba
 DEVICE=+amba:120b6000.gpio_chip
6,81,524555,-;pl061_gpio 120b7000.gpio_chip: PL061 GPIO chip @0x120b7000 registered
 SUBSYSTEM=amba
 DEVICE=+amba:120b7000.gpio_chip
6,82,531798,-;pl061_gpio 120b8000.gpio_chip: PL061 GPIO chip @0x120b8000 registered
 SUBSYSTEM=amba
 DEVICE=+amba:120b8000.gpio_chip
6,83,538982,-;pl061_gpio 120b9000.gpio_chip: PL061 GPIO chip @0x120b9000 registered
 SUBSYSTEM=amba
 DEVICE=+amba:120b9000.gpio_chip
6,84,562057,-;brd: module loaded
6,85,564768,-;hisi-sfc hisi_spi_nor.0: SPI Nor ID Table Version 1.2
 SUBSYSTEM=platform
 DEVICE=+platform:hisi_spi_nor.0
3,86,569571,-;hisi-sfc hisi_spi_nor.0: The ID: 0xa1 isn't in the BP table, Current device can't not protect
 SUBSYSTEM=platform
 DEVICE=+platform:hisi_spi_nor.0
4,87,577860,-;@spi_nor_scan(), no "m25p,fast-read".
4,88,581261,-;@spi_nor_scan(), modes->rd_modes:0xd.
6,89,584660,-;hisi-sfc hisi_spi_nor.0: (Fast) Read:  opcode=BBh, protocol=122, mode=8, wait=0
 SUBSYSTEM=platform
 DEVICE=+platform:hisi_spi_nor.0
6,90,591711,-;hisi-sfc hisi_spi_nor.0: nor->read_opcode[3: Read; 0B: Fast Read; 3B: Dual; BB: Dual IO; 6B: Quad; EB: Quad IO]: 0xbb.
 SUBSYSTEM=platform
 DEVICE=+platform:hisi_spi_nor.0
6,91,602143,-;hisi-sfc hisi_spi_nor.0: fm25q128a (Chipsize 16 Mbytes, Blocksize 64KiB)
 SUBSYSTEM=platform
 DEVICE=+platform:hisi_spi_nor.0
5,92,608588,-;5 cmdlinepart partitions found on MTD device hi_sfc
5,93,613207,-;5 cmdlinepart partitions found on MTD device hi_sfc
5,94,617813,-;Creating 5 MTD partitions on "hi_sfc":
5,95,621305,-;0x000000000000-0x000000040000 : "boot"
5,96,626787,-;0x000000040000-0x000000050000 : "env"
5,97,631751,-;0x000000050000-0x000000250000 : "kernel"
5,98,637006,-;0x000000250000-0x000000750000 : "rootfs"
5,99,642266,-;0x000000750000-0x000001000000 : "rootfs_data"
6,100,696462,-;FEPHY:addr=1, la_am=0xc, ldo_am=0x4, r_tuning=0x20
6,101,701169,-;libphy: hisi_femac_mii_bus: probed
6,102,705181,-;libphy: Fixed MDIO Bus: probed
6,103,847523,-;Generic PHY 10041100.mdio:01: attached PHY driver [Generic PHY] (mii_bus:phy_addr=10041100.mdio:01, irq=-1)
 SUBSYSTEM=mdio_bus
 DEVICE=+mdio_bus:10041100.mdio:01
4,104,857008,-;phy_id=0x20669903, phy_mode=mii
4,105,859896,-;hisi-femac 10040000.ethernet: using random MAC address 96:5e:07:51:1a:73
 SUBSYSTEM=platform
 DEVICE=+platform:10040000.ethernet
6,106,871247,-;xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
 SUBSYSTEM=platform
 DEVICE=+platform:xhci-hcd.0.auto
6,107,875460,-;xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
 SUBSYSTEM=platform
 DEVICE=+platform:xhci-hcd.0.auto
6,108,882010,-;xhci-hcd xhci-hcd.0.auto: hcc params 0x0220fe6c hci version 0x110 quirks 0x20010010
 SUBSYSTEM=platform
 DEVICE=+platform:xhci-hcd.0.auto
6,109,889437,-;xhci-hcd xhci-hcd.0.auto: irq 133, io mem 0x10030000
 SUBSYSTEM=platform
 DEVICE=+platform:xhci-hcd.0.auto
6,110,895648,-;hub 1-0:1.0: USB hub found
 SUBSYSTEM=usb
 DEVICE=+usb:1-0:1.0
6,111,898311,-;hub 1-0:1.0: 1 port detected
 SUBSYSTEM=usb
 DEVICE=+usb:1-0:1.0
6,112,901372,-;xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
 SUBSYSTEM=platform
 DEVICE=+platform:xhci-hcd.0.auto
6,113,905568,-;xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
 SUBSYSTEM=platform
 DEVICE=+platform:xhci-hcd.0.auto
6,114,912020,-;usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
 SUBSYSTEM=usb
 DEVICE=+usb:usb2
6,115,919654,-;hub 2-0:1.0: USB hub found
 SUBSYSTEM=usb
 DEVICE=+usb:2-0:1.0
6,116,922350,-;hub 2-0:1.0: hub can't support USB3.0
 SUBSYSTEM=usb
 DEVICE=+usb:2-0:1.0
6,117,1081571,-;hibvt_rtc 120e0000.rtc: rtc core: registered 120e0000.rtc as rtc0
 SUBSYSTEM=platform
 DEVICE=+platform:120e0000.rtc
6,118,1087442,-;hibvt_rtc 120e0000.rtc: RTC driver for hibvt enabled
 SUBSYSTEM=platform
 DEVICE=+platform:120e0000.rtc
6,119,1092259,-;i2c /dev entries driver
6,120,1095265,-;hibvt-i2c 12060000.i2c: hibvt-i2c0@100000hz registered
 SUBSYSTEM=platform
 DEVICE=+platform:12060000.i2c
6,121,1100787,-;hibvt-i2c 12061000.i2c: hibvt-i2c1@100000hz registered
 SUBSYSTEM=platform
 DEVICE=+platform:12061000.i2c
6,122,1106374,-;hibvt-i2c 12062000.i2c: hibvt-i2c2@100000hz registered
 SUBSYSTEM=platform
 DEVICE=+platform:12062000.i2c
6,123,1111794,-;sdhci: Secure Digital Host Controller Interface driver
6,124,1116664,-;sdhci: Copyright(c) Pierre Ossman
6,125,1119708,-;sdhci-pltfm: SDHCI platform and OF driver helper
6,126,1181127,-;mmc0: SDHCI controller on 10010000.sdhci [10010000.sdhci] using ADMA in legacy mode
6,127,1261128,-;mmc1: SDHCI controller on 10020000.sdhci [10020000.sdhci] using ADMA in legacy mode
6,128,1269458,-;NET: Registered protocol family 10
6,129,1278112,-;NET: Registered protocol family 17
6,130,1371164,-;hibvt_rtc 120e0000.rtc: setting system clock to 2021-11-10 13:51:03 UTC (1636552263)
 SUBSYSTEM=platform
 DEVICE=+platform:120e0000.rtc
6,131,1381075,-;VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
6,132,1392915,-;devtmpfs: mounted
6,133,1394797,-;Freeing unused kernel memory: 176K (c0494000 - c04c0000)
4,134,1399837,-;This architecture does not have kernel memory protection.
6,135,1744552,-;mmc0: new high speed SDHC card at address aaaa
6,136,1799111,-;mmcblk0: mmc0:aaaa SC32G 29.7 GiB
6,137,1813872,-; mmcblk0: p1
4,138,1902165,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000044)
4,139,2199847,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000044)
5,140,2199921,-;random: dd: uninitialized urandom read (512 bytes read)
4,141,2202708,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000044)
4,142,2227218,-;random: crng init done
4,143,2351557,-;FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
4,144,2357869,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000044)
4,145,2357960,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000044)
4,146,2359439,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000044)
4,147,2362176,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x0000003c)
6,148,2474213,-;IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
6,149,7780963,-;usbcore: registered new interface driver mt7601u
6,150,7861151,-;usb 1-1: new high-speed USB device number 2 using xhci-hcd
 SUBSYSTEM=usb
 DEVICE=+usb:1-1
6,151,8181173,-;usb 1-1: reset high-speed USB device number 2 using xhci-hcd
 SUBSYSTEM=usb
 DEVICE=c189:1
6,152,8353688,-;mt7601u 1-1:1.0: ASIC revision: 76010001 MAC revision: 76010500
 SUBSYSTEM=usb
 DEVICE=+usb:1-1:1.0
6,153,8367895,-;mt7601u 1-1:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
 SUBSYSTEM=usb
 DEVICE=+usb:1-1:1.0
4,154,8864980,-;mt7601u 1-1:1.0: Warning: unsupported EEPROM version 0d
 SUBSYSTEM=usb
 DEVICE=+usb:1-1:1.0
6,155,8864990,-;mt7601u 1-1:1.0: EEPROM ver:0d fae:00
 SUBSYSTEM=usb
 DEVICE=+usb:1-1:1.0
7,156,9098037,-;ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
 SUBSYSTEM=ieee80211
 DEVICE=+ieee80211:phy0
6,157,11182425,-;IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
6,158,12952984,-;wlan0: authenticate with c8:3a:35:1d:d2:40
6,159,13013182,-;wlan0: send auth to c8:3a:35:1d:d2:40 (try 1/3)
6,160,13014791,-;wlan0: authenticated
6,161,13021372,-;wlan0: associate with c8:3a:35:1d:d2:40 (try 1/3)
6,162,13024058,-;wlan0: RX AssocResp from c8:3a:35:1d:d2:40 (capab=0x411 status=0 aid=3)
6,163,13051885,-;wlan0: associated
6,164,13051953,-;IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
6,165,14345935,-;wireguard: WireGuard 1.0.20210124 loaded. See www.wireguard.com for information.
6,166,14345942,-;wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
4,167,14962902,-;sys_config: loading out-of-tree module taints kernel.
0,168,14963678,-;==== online_flag=0, cmos_yuv_flag=0, sensor=imx335, chip=hi3516ev300, board=demo====
0,169,14963683,-;==== g_quick_start_flag=0 ====
0,170,14963685,-;sysconfig init success!
0,171,14994561,-;Module himedia: init ok
6,172,14994568,-;Hisilicon Media Memory Zone Manager
0,173,14994578,-;cmz zone gfp 0x0, phys 0x42000000, nbytes 0x6000000
0,174,14994876,-;hi_osal 1.0 init success!
4,175,15025179,-;hi3516ev200_base: module license 'Proprietary' taints kernel.
4,176,15025185,-;Disabling lock debugging due to kernel taint
0,177,15067389,-;load sys.ko for Hi3516EV200...OK!
0,178,15101442,-;load region.ko for Hi3516EV200...OK!
0,179,15147154,-;load vgs.ko for Hi3516EV200...OK!
0,180,15248189,-;load vi.ko for Hi3516EV200...OK !
0,181,15291625,-;ISP Mod init!
0,182,15380793,-;load vpss.ko for Hi3516EV200...OK!
0,183,15394528,-;load chnl.ko for Hi3516EV200...OK!
0,184,15417229,-;load vedu.ko for Hi3516EV200...OK!
0,185,15452902,-;load rc.ko for Hi3516EV200...OK!
0,186,15512365,-;load venc.ko for Hi3516EV200...OK!
0,187,15555395,-;load h264e.ko for Hi3516EV200...OK!
0,188,15599901,-;load h265e.ko for Hi3516EV200...OK!
0,189,15619128,-;load jpege.ko for Hi3516EV200...OK!
0,190,15670409,-;load ive.ko for Hi3516EV200...OK!
0,191,15722063,-;Load sensor_spi.ko for Hi3516EV200...OK !
0,192,15871920,-;load mipi_rx driver successful!
0,193,15885999,-;register dev
0,194,15891470,-;Hisilicon Watchdog Timer: 0.01 initialized. default_margin=60 sec (nodeamon= 0)
0,195,15891478,-;hiwtdg init ok. ver=Oct 18 2019, 18:21:00.
3,196,16667321,-;hibvt-i2c 12060000.i2c: wait idle abort!, RIS: 0x611
 SUBSYSTEM=platform
 DEVICE=+platform:12060000.i2c
3,197,16667506,-;hibvt-i2c 12060000.i2c: wait idle abort!, RIS: 0x611
 SUBSYSTEM=platform
 DEVICE=+platform:12060000.i2c
4,198,17096067,-;alloc_contig_range: [43d80, 43dc1) PFNs busy
4,199,243170340,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000044)
4,200,243170432,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000044)
4,201,243170506,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000044)
4,202,243170622,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x0000002c)
4,203,243171412,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000044)
4,204,243171690,-;jffs2: Node totlen on flash (0xffffffff) != totlen from node ref (0x00000048)
0,205,261623994,-;Watchdog is disabled!
4,206,292076358,-;jffs2: Node CRC ffffffff != calculated CRC f09e7845 for node at 00898e90

 * killall majestic
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
.........................
root@tehshield-hi3516ev300:~# majestic
17:00:48 [    main] main@124                      Majestic Free for HiSilicon, version master+6fbbadd, built on 2021-10-08
17:00:48 [app_conf] load_config@121               Using /etc/majestic.yaml as main configuration
17:00:48 [app_conf] load_config@136               Can't read all file majestic.yaml
.........................
при ребуте камеры majestic стартует нормально
.........................
   Core dump file from /tmp/ , e.g. /tmp/majestic.806.11.1619707881.core

# Issue description
df -h показал

Filesystem                Size      Used Available Use% Mounted on
/dev/root                 4.9M      4.9M         0 100% /rom
devtmpfs                 12.8M         0     12.8M   0% /dev
/dev/mtdblock4            8.7M    364.0K      8.3M   4% /overlay
overlay                   8.7M    364.0K      8.3M   4% /
tmpfs                    60.9M         0     60.9M   0% /dev/shm
tmpfs                    60.9M      8.0K     60.9M   0% /tmp
tmpfs                    60.9M     44.0K     60.8M   0% /run
/dev/mmcblk0p1           29.7G     29,6G         0 100% /mnt/mmc

хотя в majestic.yaml указано maxUsage: 95
после заполнения SD полились ошибки jffs2  и на камере невозможно ничего изменить в настройках
после этого не помогает ни  flash_eraseall -j /dev/mtd4   ни firstboot только перепрошивка из uboot 
крутил на 4 камерах, на трех была включена запись и на всех трех эта картина, на четвертой записи не было - выжила, 

 - [ ] Any relevant log output (`logread -f`)
 - [ ] majestic.yaml configuration (`cat /etc/majestic.yaml`)

**Comment by widgetii** [comment]
Please add `df -Th` output from your camera

**Comment by zWolf-SW** [comment]
https://skr.sh/sB2dCngPcYs?a    три камеры: sd с ошибками,, без sd и нормальная sd карта

**Comment by widgetii** [comment]
Fixed long time ago: by now, writing to internal overlay is forbidden
