### ISSUE TITLE
[Feature request] Motion detection regions + sensitivity option

### ISSUE THREAD

**Issue by nitr0man** [OpenIPC/majestic#30]
хотелось бы иметь возможность указывать регионы для motion detection - игнорировать события вне регионов. пускай даже набор прямоугольников, заданных координатами х1, y1, x2, y2 в конфиге.

и хотелось бы иметь возможность регулировать чувствительность motion detection - возможно минимальный размер области детекта, возможно - threshold для отсечения помех по контрасту (или даже производное первого и второго еще добавить - чтобы большие малоконтрастные регионы движения не отсекались, но отсекались небольшие по размерам), возможно - кол-во кадров на которых присутствует движение для ивента. думаю, в имеющийся код добавить будет не очень сложно, в то же время - даст возможность подстроить чувствительность чтобы не срабатывала на мошку/пыль (минимальный размер области), шумы матрицы/пятна от света фонарей через качающиеся ветки (threshold по контрасту), пролетающих крупных насекомых/птиц в кадре (кол-во кадров на которых присутствует движение)

**Comment by guminov** [comment]
+ Подписываюсь

**Comment by flyrouter** [comment]
The request intersects with other branches and look for continuation there:
https://github.com/OpenIPC/majestic/issues/28
https://github.com/OpenIPC/majestic/issues/117
