### ISSUE TITLE
Majestic падает, если перевести подсветку в режим ШИМ

### ISSUE THREAD

**Issue by guminov** [OpenIPC/majestic#34]
* Camera board id: goke7205v200
 * OpenIPC version: master+8931ae1, 2021-12-20
 * installation method:  sysupgrade -k -r -n
 * modified majestic.yaml: yes

# Issue description

Majestic падает, если перевести подсветку в режим ШИМ командой:
``` bash
 devmem 0x100c0010 32 0x1001
```
То есть подсветка отключена в 0

# Steps to reproduce

0. Воспроизводиться только в темное время суток, при отсутствии снега))
1. Штатно загрузиться
2. Подсветка должна быть включена
3. Подключиться к консоли по SSH
4. Ввести команду:  devmem 0x100c0010 32 0x1001
5. 3-5 сек - замирает картинка, через 10 крашится majestic

[majestic.yaml.txt](https://github.com/OpenIPC/majestic_issues/files/7763544/majestic.yaml.txt)

[kmsg.log](https://github.com/OpenIPC/majestic_issues/files/7763546/kmsg.log)

[logread.log](https://github.com/OpenIPC/majestic_issues/files/7763548/logread.log)

**Comment by widgetii** [comment]
Could you check the same but with parameter `luminance` changed from `auto` to `50`?

**Comment by guminov** [comment]
Все ок - не падает. Сейчас не могу воспроизвести. Было подозрение, что отключение освещения приводит к возрастанию битрейта из-за шумов и как следствие - нехватке памяти. Сейчас битрейт около 14мбит и все работает. ШИМ видимо не причем. Можно закрывать.

**Comment by widgetii** [comment]
Please test also latest version, it should fix the issue for high bitrate

**Comment by guminov** [comment]
Все ок. При отключении подсвекти, битрейт выше 2500кбит/с не поднимается - раньше был около 14000+ кбит/с

**Comment by widgetii** [comment]
> А как отключаете подсветку. У меня при ночной сьемке битрейт шкалит за 21000кбит/с? Вернее при наступлении темноты, включатемя посдсветка, но картинка вся в шумах и на камере не щелкает затвор.

This should be fixed in latest version

**Comment by guminov** [comment]
Ну 10% - это чересчур)) достаточно 40-45, иначе ничего не разглядите. Тут чудес не случиться - недостаточность света сложно компенсировать.

**Comment by guminov** [comment]
Еще раз проверил без подсветки, почти нет других источников, темно, битрейт - 4200-4500кбит/с - это с новым маджестиком, раньше было 14000+кбит/с

**Comment by widgetii** [comment]
Could you check changing to:
```
luminance: 50
contrast: 50
```
?

**Comment by esuslik** [comment]
также падает

**Comment by widgetii** [comment]
В последней версии появилась возможность работы с профилями сенсоров (качество картинки заметно лучше в плохих условиях освещения).

В конфиг нужно добавить:
```yaml
isp:
  iqProfile: /etc/sensors/iq/imx335.ini
```

В принципе эта возможность должна также помочь в резких всплесках битрейта (что в свою очередь приводит к исчерпанию памяти и OOM kill)

**Comment by esuslik** [comment]
через веб эту настройку не сделать?
по пути /etc/sensors/iq/imx335.ini   нет такого файла. Его надо самостоятельно сделать или скачать откуда-то?

**Comment by widgetii** [comment]
Файл должен появиться после обновления прошивки.
По поводу web не скажу, возможно ее еще не добавили.

**Comment by esuslik** [comment]
после обновления, появился файл, настройки прописал. Тестируем

**Comment by esuslik** [comment]
а как-то можно проверить что опция подхватилась и работает корректно?
Видимых изменений не увидел. На одной камере битрейт поднялся пока до 4394 kbit/s. Посмотрим что будет дальше

**Comment by widgetii** [comment]
При низкой освещенности/отсутствии света должно быть значительно меньше шумов

**Comment by esuslik** [comment]
пока большой разницы  не заметил. На одной камере есть шумы и битрейт 4500, на друголй вроде и освещенность такая же, а битрей 512kbit/s и нет шумов почти

**Comment by dimerr** [comment]
Образы в которых функционал будет включен по-умолчанию собираются в данный момент.
Добавьте в конфиг 
```
isp:
  iqProfile: /etc/sensors/iq/imx335.ini

```

**Comment by esuslik** [comment]
добавлено, обновлюсь тогда завтра и потестирую

**Comment by esuslik** [comment]
прошился на master+dcf132f, 2022-07-26
Камера которая выдавала 4,5-6мбит, сейчас выдает 2,5. Шумы стали более статичные.
Раньше бегали как мошки, теперь просто раз в секунду часть меняет полжение. Видмо за счет этого битрейт меньше стал

**Comment by esuslik** [comment]
битрейт на камере упал до 2,5 за ночь не поднимался. Было несколько перезагрухзок камеры.
На второй камере с битрейтом и так было все норм. Но появились постоянные перезагрузки. Буду собирать логи по перещагрзукам
