### ISSUE TITLE
Перезагрузки камеры

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/majestic#35]
Прошил камеру 000529E9
Перезагружается 1-2 раза за 20 минут. Даже при отключеной настройке watchdog
прошил камеру 000529B2
Перестает работать сначала поток через netip(через 40 минут) и камера перезагружается.

Где и как собрать логи, чтобы предоставить вам для выявления причин перезагрузки?

Также обратил внимание на сенсор SoC temp.
При включеной подсветке и долгой работе камеры, данная температура поднимается до 116 градусов. Это нормальная температура для работы камеры? при условии что в помещении примерно 25 градусов.

**Comment by widgetii** [comment]
Which Majestic version is used currently (first line for the startup log)? Could you gather coredump and attach it here both with /etc/majestic.yaml (removing sensitive information like passwords before)

Core dump instructions are below:
```
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
   Core dump file from /tmp/ , e.g. /tmp/majestic.806.11.1619707881.core
```

**Comment by esuslik** [comment]
root@openipc-hi3516ev300:~# killall majestic; majestic
killall: majestic: no process killed
17:37:32 [    main] main@135                      Majestic Lite for HiSilicon, version master+8da5a71, built on 2022-01-19
17:37:32 [app_conf] load_config@342               Using /etc/majestic.yaml as main configuration
17:37:32 [     sdk] sdk_specific_config@3530      Using /etc/sensors/5M_imx335.ini sensor configuration file
17:37:32 [app_conf] parse_app_config@628          Main audio codec is opus (other options: mp3, aac, pcm, alaw, ulaw)
17:37:32 [app_conf] parse_app_config@681          app_config.osd_template %a %e %B %Y %H:%M:%S %Z ghgh
17:37:32 [     sdk] start_sdk@250                 App was built with MPP version: Hi3516EV200_MPP_V1.0.1.2.B030 Release
17:37:32 [     sdk] start_sdk@253                 Current MPP version: HI_VERSION=Hi3516EV200_MPP_V1.0.1.2 B030 Release
17:37:32 [    Info]                               Venc 0 stream buffer is full. 
17:37:32 [    venc] VENC_InqTask@3370             Venc 1 stream buffer is full. 
17:37:32 [    venc] VENC_InqTask@3370             Venc 0 stream buffer is full. 
17:37:32 [    venc] VENC_InqTask@3370             Venc 1 stream buffer is full.

**Comment by esuslik** [comment]
пока светло все работает в консоли показывает график синежелтый.
Как только выключаю свет, и включается подсветка то появляются строки Slow network for NETIP TCP transmit, skipping data
и majestic падает 
![изображение](https://user-images.githubusercontent.com/16290583/150375338-ddfe5700-f931-4020-9a1d-a0c32c71c0af.png)

**Comment by widgetii** [comment]
I'm still waiting for coredump

**Comment by esuslik** [comment]
[majestic.3385.11.1642694649.txt](https://github.com/OpenIPC/majestic_issues/files/7906736/majestic.3385.11.1642694649.txt)

**Comment by esuslik** [comment]
переименовал core в txt

**Comment by esuslik** [comment]
cat /etc/majestic.yaml
system:
  buffer: 1024
  logLevel: ERROR
  updateChannel: stable
image:
  mirror: false
  flip: false
  rotate: none
  contrast: auto
  hue: 50
  saturation: 50
  luminance: auto
osd:
  enabled: true
  template: "%a %e %B %Y %H:%M:%S %Z ghgh"
nightMode:
  enabled: false
  pinSwitchDelayUs: 150
  irSensorPinInvert: false
records:
  enabled: false
  path: /mnt/mmc/%Y/%m/%d/%H.mp4
  maxUsage: 95
video0:
  enabled: true
  gopMode: normal
  rcMode: avbr
  codec: h264
  size: ! "1920\u04451080"
video1:
  enabled: true
  gopMode: normal
  rcMode: avbr
  codec: h264
jpeg:
  enabled: false
  toProgressive: false
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: true
  volume: 20
  srate: 8000
  codec: opus
rtsp:
  enabled: false
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: false
  profile: outdoor
  visualize: true
  debug: true
ipeye:
  enabled: false
onvif:
  enabled: false
watchdog:
  enabled: false
  timeout: 10
isp:
  memMode: normal
  slowShutter: low
  antiFlicker: 50Hz
  rawMode: none
  sensorConfig: /etc/sensors/5M_imx335.ini
netip:
  enabled: true
  ignoreSetTime: false
  snapshots: false
  user: admin
  password: 
cloud:
  enabled: false

**Comment by esuslik** [comment]
[majestic.txt](https://github.com/OpenIPC/majestic_issues/files/7906811/majestic.txt)

**Comment by widgetii** [comment]
We found the issue and made a fix, please test against a new version

**Comment by esuslik** [comment]
после прошивки палао один раз, потом после перезагруки работает без падений. Тестирую пару дней

**Comment by esuslik** [comment]
1,5 дня аптайм самой камеры
В какой-то момент перестал работать видеопоток через netip
Через консоль видно что majestic типа работает.
При первом перезапуске majestic segmentation fault
При повторной попытке запуска ошибка:
15:08:54 [    vpss] VPSS_VI_SubmitTask@517        [grp0]:vpss unexist!
15:08:54 [      vi] VI_StartOneTask@662           ViPipe:0 sumbit vpss task fail
15:08:54 [      vb] VbDestroyPool@464             Blk in this pool(0) occupied by someone, please release first!
15:08:54 [      vb] VB_SetConfig@1733             VB is initialized!
15:08:54 [     sdk] init_mem@2547                 Cannot set VB conf
15:08:54 [     sdk] init_mem@2547                 ERR_VB_BUSY: The system is busy
15:08:54 [     sdk] start_sdk@314                 Cannot init mem
15:08:54 [    main] main@227                      Shutdown main thread

**Comment by esuslik** [comment]
на другой камере аптайм 2,5 дня, поток работает. Иногда поток не доступен или долго открывается. Как правило при включении ночной сьемки(когда становится темно). Днем и при хорошем освещении все работает быстро и без сбоев

**Comment by esuslik** [comment]
По температуре проверил 2 одинаковые камеры, на стоковой прошивке также греется ощутимо. Температура работы примерно 123 градуса.

Другая модель камеры работает на температуре 80-95 градусов. Думаю вопрос охлаждения зависит от исполнения и корпуса камеры.

**Comment by esuslik** [comment]
удалось уронить majestic просто переподключаясь к потоку чере программу partizan с телефона на андроид
дамп во вложени
[majestic.931.11.1643024962.txt](https://github.com/OpenIPC/majestic_issues/files/7925314/majestic.931.11.1643024962.txt)
и

**Comment by esuslik** [comment]
Majestic стабильно падает при переходе камеры в ночной режим.

**Comment by widgetii** [comment]
The same issue as #34 , I can recommend trying to disable hls option (set enabled to false) to mitigate the issue until it will be resolved

**Comment by esuslik** [comment]
да проблема таже. HLS отключено, но проблема всеравно воспроизводится

**Comment by widgetii** [comment]
Then we need a full log from the start to crash point, core dump, and configuration file

**Comment by esuslik** [comment]
[majestic.1035.11.1643560148.txt](https://github.com/OpenIPC/majestic_issues/files/7966369/majestic.1035.11.1643560148.txt)
[majestic.txt](https://github.com/OpenIPC/majestic_issues/files/7966371/majestic.txt)

**Comment by widgetii** [comment]
There is no full log in the attached files, all three files should be taken at the same time

**Comment by esuslik** [comment]
как снять полный лог? в уонсоли есть ограничение на кол-во строк.

**Comment by widgetii** [comment]
`majestic --logfile /full/path/to/log` as example

**Comment by esuslik** [comment]
[majestic.core.txt](https://github.com/OpenIPC/majestic_issues/files/7972680/majestic.core.txt)
[majestic.yaml.txt](https://github.com/OpenIPC/majestic_issues/files/7972681/majestic.yaml.txt)
[majesticlog.txt](https://github.com/OpenIPC/majestic_issues/files/7972683/majesticlog.txt)

Это упал мджестик при использовании приложения partizan на сматрфоне. Просмотр потока.

**Comment by esuslik** [comment]
[majestic.core.txt](https://github.com/OpenIPC/majestic_issues/files/7972713/majestic.core.txt)
[majestic.yaml.txt](https://github.com/OpenIPC/majestic_issues/files/7972714/majestic.yaml.txt)
[majesticlog.txt](https://github.com/OpenIPC/majestic_issues/files/7972715/majesticlog.txt)

это просто упал маджестик без каких-либо действий

**Comment by widgetii** [comment]
> [majestic.core.txt](https://github.com/OpenIPC/majestic_issues/files/7972680/majestic.core.txt) [majestic.yaml.txt](https://github.com/OpenIPC/majestic_issues/files/7972681/majestic.yaml.txt) [majesticlog.txt](https://github.com/OpenIPC/majestic_issues/files/7972683/majesticlog.txt)
> 
> Это упал мджестик при использовании приложения partizan на сматрфоне. Просмотр потока.

Could you clarify how I can reproduce a software crash using Partizan step-by-step? Tried many times without succeed

**Comment by esuslik** [comment]
в программе открыл поток, потом нажал кнопку назад и маджестик упал именно в этот момент и в лог написал ERROR netip:696: Unknown action 'Pause'

**Comment by widgetii** [comment]
Which Partizan version do you use? iOS or Android?

**Comment by esuslik** [comment]
android последняя версия из маркета

**Comment by widgetii** [comment]
Can you check the same issue using Partizan with audio disabled?

**Comment by esuslik** [comment]
пока не могу вопроизвести проблему. Камеры сейчас работают достаточно стабильно без перезагрузок.
Думаю данный issue можно закрыть. Создам новый если появятся перезагрузки
