### ISSUE TITLE
Подключение камеры по RTSP к облаку ipeye, нет звука

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/majestic#38]
Hi3516Ev300 +IMX335/SC4236/SC2239
000529B2
majestic master+bb20aa0, 2022-02-10

При подключении rtsp потока в облако ipeye, нет звука. В настройках облака нет возможности указать отдельный поток для audio
При подключении других камер или этой же камервы на стоковой прошивке, звук есть.

**Comment by widgetii** [comment]
Which audio codec do you use now?

**Comment by esuslik** [comment]
opus

**Comment by esuslik** [comment]
поставил alaw, все заработало
