### ISSUE TITLE
Предложение по mjpeg

### ISSUE THREAD

**Issue by vukitoso** [OpenIPC/majestic#41]
Здравствуйте.

3516ev200
HiSilicon, version master+6fbbadd, built on 2021-10-08

1) Как я понял отключить mjpeg невозможно. Предлагаю добавить отключение mjpeg через "enabled: false"

2) Я заметил что в wiki на странице https://github.com/OpenIPC/openipc-2.1/wiki/majestic_streamer указано, что mjpeg работает через url http://10.1.1.102/mjpeg.html, но у меня не заработало через этот урл.
Через http://10.1.1.102/mjpeg работает.

**Comment by widgetii** [comment]
1. MJPEG работает on-demand (если если запросы канал поднимается автоматически), в связи с этим данная настройка была удалена
2. Разница между этими двумя URL, что `/mpeg` выдает бинарный поток MJPEG, а `/mpeg.html` является минимальным веб-интерфейсом для отображения MJPEG+аудио потока
