### ISSUE TITLE
vlc rtsp rpoblem after 1 march 2022 on xm530

### ISSUE THREAD

**Issue by openIPC-tester** [OpenIPC/majestic#43]
good day

# Required information

 * Camera board id: 30695  (xm530)
 * OpenIPC version:
 * Commit: 23e8b08
 * Branch: master
 * Tag: latest
 * installation method: (sysupgrade from november version.)
 * modified majestic.yaml: yes
 * cat /dev/kmsg
 * killall majestic
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
   Core dump file from /tmp/ , e.g. /tmp/majestic.806.11.1619707881.core

# Issue description

1) on xm530 board (30695) vlc rtsp stream work well on version from 1 march 2022
(manual install, downgrade from 6 april 2022 version)

2) if update to 6 april 2022 version, vlc is connect but see freeze picture without motions of video.
ffplay can connect and see video rtsp stream

h264 stream0 on both experiments

# Expectations

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [x] Any relevant log output (`logread -f`)
 - [x] majestic.yaml configuration (`cat /etc/majestic.yaml`)

oot@openipc-xm530:~# logread -f
ffplay launch:
Apr  8 16:38:32 openipc-xm530 cron.info crond[473]: time disparity of 27490598 minutes detected
Apr  8 16:38:34 openipc-xm530 user.info majestic[541]: RTSP connection closed.
vlc launch:
Apr  8 16:39:19 openipc-xm530 user.err majestic[541]: Failed to send an RTP packet: Connection refused.
Apr  8 16:39:20 openipc-xm530 user.info majestic[541]: RTSP connection closed.

cat /etc/majestic.yaml
system:
  buffer: 1024
image:
  mirror: false
  flip: false
  rotate: none
  contrast: auto
  hue: 50
  saturation: 50
  luminance: auto
osd:
  enabled: false
  template: "%a %e %B %Y %H:%M:%S %Z"
nightMode:
  enabled: false
  pinSwitchDelayUs: 150
  irSensorPinInvert: false
records:
  enabled: false
  path: /mnt/mmc/%Y/%m/%d/%H.mp4
  maxUsage: 95
video0:
  enabled: true
  codec: h264
video1:
  enabled: false
  codec: h265
jpeg:
  enabled: true
  toProgressive: false
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: true
  volume: auto
  srate: 16000
  codec: opus
  device: hw:2
rtsp:
  enabled: true
  port: 554
hls:
  enabled: true
youtube:
  enabled: false
motionDetect:
  enabled: false
  profile: outdoor
  visualize: true
  debug: true
ipeye:
  enabled: false
onvif:
  enabled: false
watchdog:
  enabled: true
  timeout: 10

[](url)

**Comment by widgetii** [comment]
Please check recent version, we fixed timestamp issue
