### ISSUE TITLE
перезагрузка камер по обрыву соединения с регистратором

### ISSUE THREAD

**Issue by cronyx** [OpenIPC/majestic#45]
Группа камер подключенная к регистратору по netip, на котором настрена суточная перезагрузка, перезагружается вместе с регистратором.

Камеры:
Processor: hi3516ev300
firmware - Version:2.2.03.14-lite Build:master+aa4bdd6, 2022-03-14
majestic - master+912fa6f, 2022-03-08

**Comment by widgetii** [comment]
Просьба проверить свежую версию, должно быть исправлено

**Comment by cronyx** [comment]
За последние 2 дня перезагрузок больше не наблюдалось, спасибо за фикс.
