### ISSUE TITLE
Default settings for netip and onvif

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic#5]
Since our colleagues make interesting tools for automatic device firmware, please enable the onvif and netip services by default in the majestic configuration file
Thanks !

**Comment by widgetii** [comment]
They were disabled because to protect the security of inexperienced users who use the device as-is and don't want to read instructions. It's worth enabling them both only leveraging strong authorization otherwise our project will appear in CVE the next day

**Comment by widgetii** [comment]
Both of them now activated by default
