### ISSUE TITLE
Segmentation fault enabling night mode

### ISSUE THREAD

**Issue by mpissarello** [OpenIPC/majestic#54]
# Required information

 * Camera board id: IPG5020A-H-V1.0
 * CPU: Hi3516Cv100
 * Sensor: OmniVision OV2710
 * OpenIPC version: 2.2.06.24-lite
 * Build: 2022-06-24
 * Branch: master
 * Tag:
 * installation method: by manual https://github.com/OpenIPC/wiki/blob/master/ru/installation.md
 * modified majestic.yaml: yes
 * cat /dev/kmsg (reports "cat: read error: Invalid argument")
 * killall majestic
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
   Core dump file from /tmp/

# Issue description

Trying to support an IP camera with sensor OmniVision OV2710.

- dumped libsns_ov2710.so from original firmware to OpenIPC /usr/lib/sensors
- built new ov2710_i2c_dc_1080p.ini in /etc/sensors

The camera is working correctly showing the image.
Enabling "Night Mode" cause a "segmentation fault" of Majestic.

# Expectations

Working "Night Mode".

# Steps to reproduce

 1. killall majestic
 2. vi /etc/majestic.yaml -> nightMode: enabled: false
 3. Run majestic, GPIO are correctly initialized, image is present
 4. CTRL+C
 5. vi /etc/majestic.yaml -> nightMode: enabled: true
 6. Run majestic, "Segmentation fault" after start_jpeg@1273

# Information to attach

 - ipctool log from original firmware (https://github.com/OpenIPC/majestic/files/8973644/ipctool_original_firmware.log)
 - ipctool log from OpenIPC (https://github.com/OpenIPC/majestic/files/8973647/ipctool_OpenIPC.log)
 - "ipctool gpio scan" from original firmware (https://github.com/OpenIPC/majestic/files/8973652/ipctool-gpio-scan_original_firmware.log)
 - "ipctool gpio scan" from OpenIPC (https://github.com/OpenIPC/majestic/files/8973653/ipctool-gpio-scan_OpenIPC.log)
 - majestic.yaml (renamed txt) (https://github.com/OpenIPC/majestic/files/8973656/majestic.txt)
 - majestic log with night mode disabled (https://github.com/OpenIPC/majestic/files/8973657/majestic_no_night_mode.log)
 - majestic log with night mode enabled (https://github.com/OpenIPC/majestic/files/8973658/majestic_with_night_mode.log)
 - majestic core dump (https://github.com/OpenIPC/majestic/files/8973659/majestic.1717.11.1656048709.zip)
 - dmesg log from OpenIPC (https://github.com/OpenIPC/majestic/files/8973688/dmesg_OpenIPC.log)
 - "logread -f" hangs (no output shown)

# Other useful info

 - libsns_ov2710.so extracted from original firmware (https://github.com/OpenIPC/majestic/files/8973665/libsns_ov2710.zip)
 - /proc/umap/* dump from original file (https://github.com/OpenIPC/majestic/files/8973668/umap.zip)
 - ov2710_i2c_dc_1080p.ini made by me (renamed txt) (https://github.com/OpenIPC/majestic/files/8973674/ov2710_i2c_dc_1080p.txt)
 - The camera uses a IP101GR ethernet transceiver configured as MII, so the U-Boot bootargs has been modified adding these parameters: "hieth.mdioifu=0 hieth.mdioifd=0 phyaddru=0 phyaddrd=1"

**Comment by widgetii** [comment]
There is no libsns_ov2710.so and ov2710_i2c_dc_1080p.ini in master OpenIPC repository. Please make a PR first, because we don't support custom configurations

**Comment by widgetii** [comment]
Please upgrade to new version and check if it was fixed

**Comment by widgetii** [comment]
How do you switch camera from day mode to night mode and vice versa?

**Comment by mpissarello** [comment]
My fault, I misunderstood the meaning of the "night mode" parameter.

I enabled the "night mode" in the web page, then I went to the MJPEG preview and selected the light bulb icon: the IRC is switched correctly and the "Segmentation fault" is no longer shown.

The GPIO6 (CDS sensor) continues not to be triggered, but this is not the subject of this issue.
