### ISSUE TITLE
Неверное отображение даты в OSD если использовать %e в качестве даты при переходе на новый месяц.

### ISSUE THREAD

**Issue by solalex1** [OpenIPC/majestic#58]
Суть в том, что %e отображает дату двухзначным числом, используя пробел если дата меньше 10.
При переходе на новый месяц первая цифра даты предыдущего месяца (3) остается отображаться в OSD первой цифрой.
![2022-07-01_10-52-46](https://user-images.githubusercontent.com/20441408/176836431-9411fe6e-5309-4257-a5b1-98315909fe72.png)
![2022-07-01_10-54-05](https://user-images.githubusercontent.com/20441408/176836488-27be61e8-ba73-46c1-b876-434eef51c592.png)

**Comment by mariarti** [comment]
16ev300 same here
![photo_2022-12-04_20-41-10](https://user-images.githubusercontent.com/1933140/205511803-d12cdf64-0753-4850-918b-c71f90704ded.jpg)
![photo_2022-12-04_20-41-29](https://user-images.githubusercontent.com/1933140/205511806-ffd03595-fbb7-4f5a-a705-27ec069098dc.jpg)
after reboot 
![photo_2022-12-04_20-41-35](https://user-images.githubusercontent.com/1933140/205511817-157c71e2-f259-47f8-9a36-42be574b9f2d.jpg)

**Comment by widgetii** [comment]
The issue was that "rendering" of spaces were skipped (as premature optimization). Fixed
