### ISSUE TITLE
Не работает авторизация rtsp потока

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/majestic#61]
Перестала работать авторизация на rtsp потоке

Дает просматривать поток через vlc без авторизации

**Comment by widgetii** [comment]
Нужно больше деталей, проверил на свежем релизе - все по-прежнему работает

**Comment by esuslik** [comment]
версия majestic overlay master+570472c, 2022-07-25
открываю поток через vlc ссылкой rtsp://10.199.200.183:554/stream=0
И поток открывается не запрашивая авторизации

**Comment by widgetii** [comment]
Покажите вывод `cat /etc/shadow`

**Comment by esuslik** [comment]
![изображение](https://user-images.githubusercontent.com/16290583/180833407-80509bcd-fae9-4b0a-bd01-60734a7efd69.png)

**Comment by widgetii** [comment]
Судя по файлу, никакого пароля не установлено

**Comment by esuslik** [comment]
а на какого пользователя должен стоять пароль? на root?
а в потоке уазывать? rtsp://root:pass@10.199.200.183:554/stream=0

**Comment by widgetii** [comment]
Пароль устанавливается на root, в rtsp можно использовать пользователя либо root, либо admin

**Comment by esuslik** [comment]
Да, все работает. Я не правльно думал как оно должно работать
