### ISSUE TITLE
When enable ONVIF in the settings, the streamer crashes and does not turn on.

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic#62]
После правок настроек majestic через веб-интерфейсе (например включаем onvif), при сохранении, стример падает с `Segmentation fault` и не стартует автоматически, требуется перезагрузка устройства.

Проверено на устройствах с процессорами hi3518ev200, hi3516cv300, hi3516ev300

**Comment by widgetii** [comment]
Reproduces on latest build just by `killall -1 majestic`

273af7b709f44e96235bef6913bc928adb9736fc is the first bad commit

**Comment by widgetii** [comment]
Thank you for report, fixed in latest build
