### ISSUE TITLE
[bug] 3516CV100 Segmentation fault

### ISSUE THREAD

**Issue by mariarti** [OpenIPC/majestic#64]
# Required information

 * Camera board id: 3516CV100 (53H20PL-S)
 * OpenIPC version: master+6584a59, 2022-07-27
 * Majestic: Lite master+bf58520, 2022-07-26
 * modified majestic.yaml: yes

# Issue description

After ~ 6 hours got "Segmentation fault"
Even if debugging turned on, it doesn't work. (no coredumps,etc)
![Screenshot 2022-07-28 at 23-19-39 Majestic debugging - OpenIPC](https://user-images.githubusercontent.com/1933140/181639799-f49b6ef9-0394-4855-9503-e9755524c71c.png)
![Screenshot 2022-07-28 at 23-22-34 Majestic settings - OpenIPC](https://user-images.githubusercontent.com/1933140/181640042-1b3469fa-d290-4244-a528-30d5f401de93.png)
[S95hisilicon.txt](https://github.com/OpenIPC/majestic/files/9214307/S95hisilicon.txt)
No "Log of last core dumping" exist 
No "Upload to FTP server" performed
Guess "Upload core dump to developers" not done (because of 1st previous)

OS still go on (wdt don't trigger reboot)

```
root@openipc-hi3516cv100:~# lsmod
Module                  Size  Used by    Tainted: P  
wdt                     4229  2 
hi3518_adec            16816  1 
hi3518_aenc            53768  1 
hi3518_ao              45334  1 
hi3518_ai              52883  1 
hi3518_sio             12541  3 hi3518_ao,hi3518_ai
hidmac                 13593  2 hi3518_ao,hi3518_ai
acodec                 10375  0 
ssp_sony                4833  0 
pwm                     1489  0 
hi_i2c                  3792  0 
hi3518_ive             32474  1 
hi3518_region          51623  2 
hi3518_rc             152960  1 
hi3518_jpege           46592  1 
hi3518_h264e          162380  1 
hi3518_chnl            39989  1 
hi3518_group          179421  3 
hi3518_venc            92908  6 hi3518_jpege,hi3518_h264e
hi3518_vpss           208990  4 
hi3518_isp             21668  5 ssp_sony,hi_i2c
hi3518_viu            181403  3 
hi3518_dsu            129358  1 
hi3518_tde            117632  1 hi3518_dsu
hiuser                   890  2 hi3518_jpege,hi3518_h264e
hi3518_sys             40940  3 hi3518_viu
hi3518_base            44314 21 hi3518_adec,hi3518_aenc,hi3518_ao,hi3518_ai,hi3518_sio,acodec,hi3518_ive,hi3518_region,hi3518_rc,hi3518_jpege,hi3518_h264e,hi3518_chnl,hi3518_group,hi3518_venc,hi3518_vpss,hi3518_isp,hi3518_viu,hi3518_dsu,hi3518_sys
mmz                    19773  4 hi3518_aenc,hi3518_h264e,hi3518_tde,hi3518_base
vfat                    9113  0 
fat                    44178  1 vfat
```

# Steps to reproduce

 1. Launch camera
 2. wait
 3. Segmentation fault
 
# Information to attach
[majestic.zip](https://github.com/OpenIPC/majestic/files/9214277/majestic.zip)
[log.zip](https://github.com/OpenIPC/majestic/files/9214280/log.zip)
`logread -f` is absolutely clear, no records about or related to  segmentation fault

**Comment by mariarti** [comment]
My assumption about WDT is that in /etc/init.d/S95hisilicon execute /usr/sbin/sendcoredump.sh which execute
```
log "Stopping watchdog"
rmmod wdt
log "done"
```
but further i guess something went wrong and no core dumps including expected reboot.

**Comment by skilurius** [comment]
Related https://github.com/OpenIPC/majestic/issues/171
