### ISSUE TITLE
Падает majestic при включении motion guard

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/majestic#65]
hi3516ev300 (hi3516ev300 family), imx335, 16 MB Flash, 2.2.07.28-lite, openipc-hi3516ev300
firmware master+702332d, 2022-07-28
majestic master+a0a0d48, 2022-07-28

Включаем в настройках mjestic steramer:
.system.logLevel: DEBUG
.motionDetect.enabled: true
.motionDetect.visualize: true
.motionDetect.debug: true

В services настраиваем отправку на email (на фтп таже история)

Включем плагин motion guard 
motion_sensitivity="4"
motion_send2email="true" или ftp, не важно

Через несколько минут majestic падает. Если перезапустить majestic с консоли, то не падает.
Причем когда падает маджестик то он не отправляет корку на фтп и не пишет ее на саму камеру. 
Watchdog не всегда срабатывает, стоит таймацт 180сек.

**Comment by widgetii** [comment]
Максимальный возможный таймаут у HiSilicon - 59 секунд

**Comment by widgetii** [comment]
Уточните вывод `free` на вашей системе

**Comment by esuslik** [comment]
![image](https://user-images.githubusercontent.com/16290583/181698455-73662836-1b9a-427a-a35c-e0417487a475.png)

**Comment by esuslik** [comment]
маджестик упал минут 40 назад. watchdog не сработал. 
сейчас маджестик так и на запущен и вывод free в этот момент

![image](https://user-images.githubusercontent.com/16290583/181711269-0757e34d-1b6d-4164-99de-8f6a89c89161.png)

**Comment by esuslik** [comment]
[dump.core.txt](https://github.com/OpenIPC/majestic/files/9225549/dump.core.txt)
[majestic.yaml.txt](https://github.com/OpenIPC/majestic/files/9225550/majestic.yaml.txt)
