### ISSUE TITLE
Web interface does not allow to enter 0

### ISSUE THREAD

**Issue by carbofos** [OpenIPC/majestic#69]
Majestic settings -> Night Mode -> GPIO pins
On zero value I get a message
```
Value must be greater than or equal 1
```

**Comment by widgetii** [comment]
For Majestic it also is not valid GPIO number

**Comment by themactep** [comment]
0 pin included in allowed values on web.

**Comment by themactep** [comment]
please test and close the ticket if it works

**Comment by widgetii** [comment]
Fixed now in Majestic
