### ISSUE TITLE
[improvement] automatic switch day/night correction value

### ISSUE THREAD

**Issue by cronyx** [OpenIPC/majestic#72]
При отсутствии датчика света, ночной режим включается автоматически "по картинке". При включении IR подсветки значние ISO уменьшается до ~6000, а дневной режим активирется уже при 80000, потому в данном режиме, ночью, происходит циклическая смена дневного и ночного режима. Нужно какое-то значение компенсации, чтобы иметь возможность устанавливать порог отключения ночного режима.

**Comment by flyrouter** [comment]
Done
