### ISSUE TITLE
Change gpio limit for night mode.

### ISSUE THREAD

**Issue by khseal** [OpenIPC/majestic#75]
У меня GPIO 120 и 121. Процессор HI3516DV100. При прописывании гпио получаю ошибку 

Sep 12 13:05:25 openipc-hi3516dv100 user.err majestic[941]: Can't parse param 'irCutPin1' value '120'. Value '120' is not in a range [0; 99].
Sep 12 13:05:25 openipc-hi3516dv100 user.err majestic[941]: Can't parse param 'irCutPin2' value '121'. Value '121' is not in a range [0; 99].

**Comment by widgetii** [comment]
Fixed in the latest build
