### ISSUE TITLE
[bug] *.heif format issue

### ISSUE THREAD

**Issue by mariarti** [OpenIPC/majestic#76]
# Issue description
16ev300
When trying to convert heif with linux (Ubuntu) tools, there is a problem. Probably something with `"Non-existing item ID referenced: 'pitm' box references a non-existing image"`.

# Expectations
successful convert
# Steps to reproduce
```
apt install libheif-examples
$ heif-info image.heif 
MIME type: image/heif
main brand: mif1
compatible brands: mif1, heic

Could not read HEIF/AVIF file: Invalid input: Non-existing item ID referenced: 'pitm' box references a non-existing image
```

```
sudo apt install imagemagick

$ convert image.heif -quality 95 output.JPG
convert-im6.q16: no images defined `output.JPG' @ error/convert.c/ConvertImageCommand/3229.

$ convert image.heic -quality 95 output.JPG
convert-im6.q16: no images defined `output.JPG' @ error/convert.c/ConvertImageCommand/3229.
```
# Information to attach
![err-heif](https://user-images.githubusercontent.com/1933140/189683551-863e07bd-f767-4507-946d-e091c068fc3c.png)

**Comment by mariarti** [comment]
Problem founded: video0 stream should be H265, mine was H264.
It works fine.
```
$ heif-info image.heif 
MIME type: image/heif
main brand: mif1
compatible brands: mif1, heic

image: 2592x1944 (id=1), primary
  color profile: no
  alpha channel: no 
  depth channel: no
```

**Comment by themactep** [comment]
It seems that HEIF image from H.264 codec is malformed. And while both files have image in .mdata box, the reference from .pitm is missing or points to a wrong box/format.

The image taken from h.264 codec is broken
```
$ heif-info image264.heif 
MIME type: image/heif
main brand: mif1
compatible brands: mif1, heic

Could not read HEIF/AVIF file: Invalid input: Non-existing item ID referenced: 'pitm' box references a non-existing image
```
while one from h.265 is fine
```
$ heif-info image265.heif 
MIME type: image/heif
main brand: mif1
compatible brands: mif1, heic

image: 2592x1944 (id=1), primary
  color profile: no
  alpha channel: no 
  depth channel: no
```

Comparison of outputs from `heif-info -d <imagefile>` shows slight difference in .ipco data.

![Screenshot from 2022-09-12 13-56-06](https://user-images.githubusercontent.com/37488/189723773-2fbf7b11-aed7-4c0e-872d-3f276ad4c851.png)

**Comment by themactep** [comment]
[images.zip](https://github.com/OpenIPC/majestic/files/9550652/images.zip)

**Comment by widgetii** [comment]
<img width="1054" alt="Screenshot 2022-09-13 at 19 41 21" src="https://user-images.githubusercontent.com/6576495/189958775-6a9eaf45-0e1a-41fc-ade1-c011bda4b6c8.png">
Both files can be opened under MacOS using standard image preview application

As far as I know, libheif still [doesn't support](https://github.com/strukturag/libheif#compiling) HEIF format based on H.264 codec (only H.265 and AV1), and I have no idea how to prove correctness of H.264 codec support on platforms other than MacOS (and few people reported they opened these files on their Android phones as well)

**Comment by widgetii** [comment]
I took once more time to study libheif source code, there is no support for other codecs that H.265/AV1 now (take a look into [https://github.com/strukturag/libheif/tree/master/libheif/](source code) files `heif_decoder_*.cc` and I didn't find requests/issues/PRs to support H.264 codec)

As for me, one should make a PR to libheif repo with adding corresponding plugins with H.264 decoding libraries that will resolve the issue

**Comment by themactep** [comment]
Right, libheif README says:
```
libheif has support for decoding
...
* plugin interface to add alternative codecs for additional formats (AVC, JPEG)
```

So we need at least to find a fork with an AVC plugin.

**Comment by widgetii** [comment]
Libheif authors are authors of libde265 library, so they build new one on top of existing codebase. It's better to ask if they ever like new PR with H.264 support and more importantly which library they suggest integrating for decoding such images.
