### ISSUE TITLE
Audio input (mic) for Majestic on Ingenic T10 not working

### ISSUE THREAD

**Issue by brainstorm** [OpenIPC/majestic#77]
[As discussed over Telegram](https://t.me/openipc/33950).

![photo_2022-09-23 16 55 57](https://user-images.githubusercontent.com/175587/191906830-b18352fc-589d-42f4-9e25-99e7d09f6cf0.jpeg)

**Comment by brainstorm** [comment]
There's some audio SDK example ready to be integrated from the Russian Telegram channel: https://t.me/openipc_modding/184685

**Comment by widgetii** [comment]
I still don't have such type of hardware in my lab

**Comment by skilurius** [comment]
No hardware available for testing.
