### ISSUE TITLE
Purple image when switching night mode

### ISSUE THREAD

**Issue by kasitoru** [OpenIPC/majestic#83]
Заметил интересный момент при смене режима с дневного на ночной - на некоторое время картинка становится фиолетовой, буквально на пол секунды, спустя которые становится все нормально, черно-белое. На родной прошивке такого не наблюдается. Такое ощущение, что ИК подсветка уже включилась, но картинка еще не успела переключиться в grayscale режим.

![image](https://user-images.githubusercontent.com/16743879/200388839-d5381173-70a8-4c56-b1e5-6a2667cb2e08.jpg)

https://github.com/OpenIPC/device-mjsxj02hl

**Hardware**
Processor hi3518ev300
Family hi3516ev200
Sensor jxf22_i2c
Flash 16 MB

**Firmware**
Version 2.2.11.05-lite
Build master+fe6cf7e8, 2022-11-05
Majestic HEAD+1c1718e, 2022-11-05

**Comment by ZigFisher** [comment]
Желательно описать последовательность действий которая предполагается
У нас есть переключение ISP в день/ночь, есть управление ИК фильтром, есть включение подсветки.

**Comment by kasitoru** [comment]
Когда реверсил родную прошивку, то для ночного режима там был следующий алгоритм:

1. Переключение картинки в grayscale
2. Открытие ИК фильтра
3. Включение ИК подсветки

Соответственно при переходе в дневной режим все выполнялось в обратной последовательности.

https://github.com/kasitoru/mjsxj02hl_application/blob/main/localsdk/night/night.c

**Comment by brainstorm** [comment]
Same issue with an Ingenic T10 camera (real color, blue, photo taken with an iPhoneXS for comparison).

Firmware: Majestic | Lite, master+87a47c1, 2022-09-15

![Screen Shot 2022-12-14 at 11 18 31 am](https://user-images.githubusercontent.com/175587/207473364-f69a7c8a-5106-4b9b-878a-345a16d519d7.png)
![IMG_2468](https://user-images.githubusercontent.com/175587/207473455-213c4633-1099-4249-a4f4-00ea277930e4.JPG)

**Comment by flyrouter** [comment]
Done
