### ISSUE TITLE
Problem with night mode after majestic restart

### ISSUE THREAD

**Issue by kasitoru** [OpenIPC/majestic#84]
Если при включенном ночном режиме перезагрузить Majestic, то возникает проблема - картинка остается ч/б, но ик подсветка отключается (и, возможно, закрывается шторка фильтра).

**Как воспроизвести:**

1. Останавливаем сервис автоматического переключения режимов день/ночь (на моей камере нет ик сенсора и приходится использовать самописный скрипт на основе анализа значения isp_again):

    `/etc/init.d/S96autonight stop`

2. В веб интерфейсе в разделе "Preview" тыкаем кнопочку "Toggle night mode", чтобы перевести камеру в ночной режим. Убеждаемся что картинка стала ч/б и ИК подсветка включена.

3. Перезапускаем Majestic:

    `killall -1 majestic`

4. В итоге получаем ч/б изображение с отключенной ИК подсветкой. Но в `http://<cam_ip>/metrics` при этом значение `night_enabled` равно единице, т.е. ночной режим активирован (но, получается, не до конца).

Если после этого вручную щелкнуть пару раз по кнопке "Toggle night mode", то нормальная работа восстанавливается.

Собственно, я вижу тут два решения - либо починить восстановление последнего состояния ночного режима после перезагрузки, либо при старте majestic принудительно устанавливать дневной режим с отключенным grayscale и night_enabled (в metrics).

Прикладываю два изображения. Первое - "правильный" ночной режим, когда ИК подсветка включена и шторка фильтра открыта. Второе - описанная выше проблема.

![1](https://user-images.githubusercontent.com/16743879/200569149-a14a3ac9-a77f-4c28-a3e9-742dd48f3cd2.jpg)
![2](https://user-images.githubusercontent.com/16743879/200569193-a3a69b87-626a-4c9f-8bad-44c0d92e2d5f.jpg)

**UPDATE 1:** как выяснилось, это воспроизводится только при таком перезапуске:

`killall -1 majestic`

Если перезапускать без аргумента `-1`, то все нормально (ночной режим отключается полностью, и после загрузки камера находится в дневном режиме с цветной картинкой, отключенной подсветкой и закрытым фильтром):

`killall majestic; sleep 3; majestic`

Тем не менее, это не решение проблемы - изначально баг выявился при автоматической перезагрузке majestic после сохранения его настроек через веб интерфейс, а там как раз используется `killall -1 majestic`.

**Comment by kasitoru** [comment]
Стоит ли ожидать подтверждения бага и его исправления?

**Comment by widgetii** [comment]
Стоит в очереди как проблема с низким приоритетом

**Comment by widgetii** [comment]
Правильно ли я понимаю, что проблема только в отключении подсветки при `killall -1 majestic`? Используется вариант с управлением через единый GPIO `backlightPin`?

**Comment by kasitoru** [comment]
Именно так.

**Comment by widgetii** [comment]
Алгоритм изменен на исключение повторной инициализации `backlightPin` при перезапуске с конфигурированием

**Comment by kasitoru** [comment]
Обновился до `master+31b582d, 2022-12-09`, проблема все еще присутствует.

**Comment by widgetii** [comment]
Покажите логи majestic после получения `killall -1 majestic`

**Comment by widgetii** [comment]
Запустите из командной строки, не вижу переключения, не вижу переключения в `set_gpio`

**Comment by kasitoru** [comment]
Как? При `killall -1 majestic` в терминал ничего не выводится.

**Comment by widgetii** [comment]
`killall majestic; sleep 2; majestic`, а в соседнем терминале `killall -1 majestic`

**Comment by widgetii** [comment]
`backlightPin` в данном случае 54?

**Comment by kasitoru** [comment]
Верно

**Comment by kasitoru** [comment]
Так это лог после `killall -1 majestic` и там как раз

`15:14:39 < majestic> [ gpio] set_gpio@25 set_gpio(54, 0)`

**Comment by widgetii** [comment]
```
19:38:20  <       majestic> [    gpio] set_gpio@25                   set_gpio(10, 0)
19:38:20  <       majestic> [    gpio] set_gpio@25                   set_gpio(11, 0)
19:38:20  <       majestic> [    gpio] set_gpio@25                   set_gpio(54, 0)
19:38:20  <       majestic> [    gpio] set_gpio@25                   set_gpio(10, 1)
19:38:20  <       majestic> [    gpio] set_gpio@25                   set_gpio(11, 0)
19:38:20  <     iq_monitor> [     sdk] monitor_thread@358            Current ISO 105
19:38:20  <     iq_monitor> [   scene] SCENE_SetDynamic3DNR_V3@1651  ISO: 105, Level: 1, Count: 12
19:38:20  <       majestic> [    gpio] set_gpio@25                   set_gpio(10, 0)
19:38:20  <       majestic> [    gpio] set_gpio@25                   set_gpio(11, 1)
19:38:20  <       majestic> [    gpio] set_gpio@25                   set_gpio(10, 0)
19:38:20  <       majestic> [    gpio] set_gpio@25                   set_gpio(11, 0)
...
19:14:12  <       majestic> [  levent] signal_hup_cb@78              Signal HUP received, reloading config
19:14:12  <       majestic> [    gpio] set_gpio@25                   set_gpio(10, 0)
19:14:12  <       majestic> [    gpio] set_gpio@25                   set_gpio(11, 0)
19:14:13  <       majestic> [    gpio] set_gpio@25                   set_gpio(10, 0)
19:14:13  <       majestic> [    gpio] set_gpio@25                   set_gpio(11, 0)
19:14:13  <       majestic> [    gpio] set_gpio@25                   set_gpio(10, 1)
19:14:13  <       majestic> [    gpio] set_gpio@25                   set_gpio(11, 0)
19:14:13  <     iq_monitor> [     sdk] monitor_thread@358            Current ISO 105
19:14:13  <     iq_monitor> [   scene] SCENE_SetDynamic3DNR_V3@1651  ISO: 105, Level: 1, Count: 12
19:14:13  <       majestic> [    gpio] set_gpio@25                   set_gpio(10, 0)
19:14:13  <       majestic> [    gpio] set_gpio@25                   set_gpio(11, 1)
19:14:13  <       majestic> [    gpio] set_gpio@25                   set_gpio(10, 0)
19:14:13  <       majestic> [    gpio] set_gpio@25                   set_gpio(11, 0)
```

Подобное поведение у меня не воспроизводится (поставил тоже `54` для наглядности, дергается только один раз). Нужен ваш `/etc/majestic.yaml`

**Comment by kasitoru** [comment]
```
system:
  buffer: 1024
  staticDir: /var/www/majestic
isp:
  iqProfile: /etc/sensors/iq/f23.ini
image:
  mirror: true
  flip: true
  rotate: none
  contrast: 50
  hue: 50
  saturation: 50
  luminance: 50
osd:
  enabled: false
  template: "OpenIPC v.2.2 | %F %T %Z"
nightMode:
  enabled: true
  irCutPin1: 70
  irCutPin2: 68
  backlightPin: 54
  dncDelay: 10
records:
  enabled: false
  path: /mnt/mmcblk0p1/%Y/%m/%d/%H/%M.mp4
  maxUsage: 95
video0:
  enabled: true
  codec: h264
video1:
  enabled: false
jpeg:
  enabled: true
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 2048
audio:
  enabled: true
  volume: 70
  srate: 8000
  codec: pcm
  outputEnabled: true
  speakerPin: 55
  speakerPinInvert: false
  voiceEqualizer: common
rtsp:
  enabled: true
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: false
  visualize: true
  debug: true
ipeye:
  enabled: false
netip:
  enabled: false
  user: admin
  password: 12345
  port: 34567
  snapshots: true
  ignoreSetTime: false
onvif:
  enabled: false
watchdog:
  enabled: true
  timeout: 30
```

**Comment by widgetii** [comment]
```
19:21:01  <       majestic> [    main] main@125                      Majestic Lite for HiSilicon, version master+fa278f4, built on 2022-12-08
19:21:01  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
19:21:01  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)
**19:21:01  <       majestic> [    gpio] set_gpio@25                   set_gpio(54, 0)**
19:21:01  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 1)
19:21:01  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)
19:21:01  <     iq_monitor> [     sdk] monitor_thread@358            Current ISO 105
19:21:01  <     iq_monitor> [   scene] SCENE_SetDynamic3DNR_V3@1651  ISO: 105, Level: 1, Count: 9
19:21:02  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
19:21:02  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 1)
19:21:02  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
19:21:02  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)
...
19:21:25  <       majestic> [  levent] signal_hup_cb@78              Signal HUP received, reloading config
19:21:25  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
19:21:25  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)
19:21:26  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
19:21:26  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)
19:21:26  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 1)
19:21:26  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)
19:21:26  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
19:21:26  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 1)
19:21:27  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
19:21:27  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)
```

Также только один раз, у вас hi3518ev300?

**Comment by kasitoru** [comment]
Да. Конфиги отсюда, без каких либо правок (кроме данных беспроводной сети) https://github.com/OpenIPC/device-mjsxj02hl

**Comment by widgetii** [comment]
А как обновляли Majestic?

**Comment by kasitoru** [comment]
Запуск `updatemajestic.sh` через терминал

**Comment by kasitoru** [comment]
Перепрошил камеру заново, обновил majestic и снова выполнил шаги из первого поста для повторения бага. Проблема осталась, но теперь в логе нет упоминания о смене состояния пина 54:

> 17:05:10  <       majestic> [  levent] signal_hup_cb@78              Signal HUP received, reloading config
> 17:05:10  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
> 17:05:10  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)
> 17:05:10  <       majestic> [   audio] deinit_audio_in@537           audio system is deinitialized
> 17:05:10  <       majestic> [     sdk] stop_chn@1954                 Stopped 1 channel
> 17:05:10  <       majestic> [     sdk] stop_chn@1954                 Stopped 0 channel
> 17:05:10  <      hi_logger> [      vi] VI_WaitCaptureFrameStop@2280  Wait Pipe 0 Capture stop timeout 120ms!!!
> 17:05:10  <       majestic> [     sdk] stop_sdk@3192                 Stop sdk Ok!
> 17:05:10  <       majestic> [app_conf] load_config@89                Using /etc/majestic.yaml as main configuration
> 17:05:10  <       majestic> [app_conf] parse_app_config@282          Main audio codec is pcm (other options: opus, aac, alaw, ulaw)
> 17:05:10  <       majestic> [     sdk] try_sensor_config@3277        SENSOR=jxf22
> 17:05:10  <       majestic> [     sdk] find_sensor_config@3240       matched sensor config: jxf22_i2c_1080p.ini
> 17:05:10  <       majestic> [     sdk] start_sdk@407                 Using /etc/sensors/jxf22_i2c_1080p.ini sensor configuration file
> 17:05:10  <       majestic> [     sdk] start_sdk@416                 App was built with MPP version: Hi3516EV200_MPP_V1.0.1.2.B030 Release
> 17:05:10  <       majestic> [     sdk] start_sdk@419                 Current MPP version: HI_VERSION=Hi3516EV200_MPP_V1.0.1.2 B030 Release
> 17:05:11  <       majestic> [     sdk] start_sdk@439                 sensor stSnsSoiSensorObj
> 17:05:11  <       majestic> [     sdk] start_sdk@444                   input_mode MIPI, WDR NONE
> 17:05:11  <       majestic> [     sdk] start_sdk@451                   dev [1920x1080]@200x20 25fps, BGGR
> 17:05:11  <       majestic> [  sensor] try_to_load@19                trying to load /usr/lib/sensors/libsns_f22.so
> 17:05:11  <       majestic> [     hal] hisi_free_mem_ex@755          Free MMZ mem before allocation: 29664KB
> 17:05:11  <       majestic> [     sdk] dump_vb_configuration@2163    VB configuration:
> 17:05:11  <       majestic> [     sdk] dump_vb_configuration@2173      [0]: 3110400 x 3
> 17:05:11  <       majestic> [     sdk] dump_vb_configuration@2173      [1]: 2592000 x 1
> 17:05:11  <       majestic> [     hal] hisi_free_mem_ex@755          Free MMZ mem after allocation: 18008KB
> 17:05:11  <       majestic> [    puts]                               >> sensor_global_init()
> 17:05:11  <       majestic> [    puts]                               << sensor_global_init()
> 17:05:11  <       majestic> [    puts]                               >> cmos_get_ae_default()
> 17:05:11  <       majestic> [    puts]                               << cmos_get_ae_default()
> 17:05:11  <       majestic> [     sdk] init_sensor@2359              Sensor driver loaded
> 17:05:11  <       majestic> [     sdk] init_vi@2808                  SDK is in 'VI_OFFLINE_VPSS_OFFLINE' mode
> 17:05:11  <       majestic> [     log] printf@268                    >> cmos_set_wdr_mode(): 0
> [Func]:cmos_set_wdr_mode [Line]:743 [Info]:linear mode
> 17:05:11  <       majestic> [    puts]                               << cmos_set_wdr_mode()
> 17:05:11  <       majestic> [    puts]                               >> cmos_set_image_mode()
> 17:05:11  <       majestic> [    puts]                               >> cmos_get_isp_default()
> 17:05:11  <       majestic> [    puts]                               << cmos_get_isp_default()
> [Func]:HI_ISP_Init [Line]:524 [Info]:ISP[0] DngInfo not initialized in Cmos.c!
> 17:05:11  <       majestic> [    puts]                               >> cmos_get_ae_default()
> 17:05:11  <       majestic> [    puts]                               << cmos_get_ae_default()
> [Func]:DrcCheckCmosParam [Line]:2080 [Info]:Invalid enOpType!
> 17:05:11  <       majestic> [     log] printf@268                    [JXF22] Date: Oct  9 2019
> 17:05:11  <       majestic> [     log] printf@268                    [JXF22] Time: 14:20:22
> 17:05:11  <       majestic> [    puts]                               >> soi_sensor_init()
> 17:05:11  <       majestic> [    puts]                               >> soi_sensor_linear_1080p30_init()
> 17:05:11  <       majestic> [    puts]                               << soi_sensor_linear_1080p30_init()
> 17:05:11  <       majestic> [    puts]                               << soi_sensor_init()
> 17:05:11  <       majestic> [     sdk] log_venc_chn@1254             H.264 1920x1080 25fps 4096Kbit  25 GOP
> 17:05:11  <     iq_monitor> [     sdk] monitor_thread@336            Loading IQ profile /etc/sensors/iq/f23.ini
> 17:05:11  <       majestic> [     sdk] create_vpss_chn@1001            new venc: 0   vpss_grp: 0,   vpss_chn: 0
> 17:05:11  <       majestic> [     hal] show_blocks@686                 allocated Rcn x 2=6160, Str x 1=1528, PInfo x 2=264, Node x 1=36
> 17:05:11  <       majestic> [     sdk] start_video@1913                venc took 7988KB of MMZ [1518]
> 17:05:11  <      hi_logger> [      vi] VI_DRV_CapIsWrongInt@7785     Pipe:0 err intterupt status:0x1001a !! EOF:2 BUFOVF:0 DATATHROW:8 .
> 17:05:11  <       majestic> [   audio] init_audio_in@478             Ai(0,0) bind to AencChn:0 ok!
> 17:05:11  <       majestic> [     sdk] start_sdk@536                   Audio took 388KB of MMZ
> 17:05:11  <       majestic> [    gpio] set_gpio@25                   set_gpio(55, 0)
> 17:05:11  <       majestic> [    play] init_audio_out@323            bind adec:0 to ao(0,0) ok
> 17:05:11  <       majestic> [     sdk] start_sdk@551                 HiSilicon SDK started
> 17:05:11  <      hi_logger> [      vi] VI_DRV_GetFrmVbBlk@4106       Pipe 0 chn 0 get buffer fail,size 2592000 !
> 17:05:11  <      hi_logger> [      vi] VI_COMM_CapPrepareFrame@2915  pipe id 0 get vb fail
> 17:05:11  <      hi_logger> [    vpss] vpss_drv_prepare_new_vb@6327  [grp0 chn0]:get buffer fail,size 3110400 !
> 17:05:11  <       majestic> [     hal] hisi_free_mem_ex@755          Free MMZ mem finally: 5868KB
> 17:05:11  <       majestic> [   httpd] new_http_server@370           HTTP server started on :::80
> 17:05:11  <       majestic> [    rtsp] rtsp_init@31                  RTSP server started on port 554
> 17:05:11  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
> 17:05:11  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)
> 17:05:11  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 1)
> 17:05:11  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)
> 17:05:11  <      hi_logger> [    vpss] vpss_drv_prepare_new_vb@6327  [grp0 chn0]:get buffer fail,size 3110400 !
> 17:05:11  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
> 17:05:11  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 1)
> 17:05:12  <       majestic> [    gpio] set_gpio@25                   set_gpio(70, 0)
> 17:05:12  <       majestic> [    gpio] set_gpio@25                   set_gpio(68, 0)

Чудеса!

**Comment by widgetii** [comment]
Если GPIO, отвечающее за подсветку, при перезапуске не перевыставляется в 0, то как сбрасывается подсветка?

**Comment by kasitoru** [comment]
Я не знаю, но она же сбрасывается. Сейчас попробую вручную поэкспериментировать с переключением этих пинов.

**Comment by widgetii** [comment]
Как догадка: возможно проблема в том, что инит GPIO происходит в любом случае, эквивалент: `echo out > /sys/class/gpio/gpio54/direction`

**Comment by kasitoru** [comment]
Через кнопку в веб интерфейсе включил ночной режим. После решил повторить последовательность из лога, и на включении пина 68 подсветка отключилась!

```
17:05:11 < majestic> [ gpio] set_gpio@25 set_gpio(70, 0)
17:05:11 < majestic> [ gpio] set_gpio@25 set_gpio(68, 0)
17:05:11 < majestic> [ gpio] set_gpio@25 set_gpio(70, 1)
17:05:11 < majestic> [ gpio] set_gpio@25 set_gpio(68, 0)

17:05:11 < majestic> [ gpio] set_gpio@25 set_gpio(70, 0)
17:05:11 < majestic> [ gpio] set_gpio@25 set_gpio(68, 1) <----
17:05:12 < majestic> [ gpio] set_gpio@25 set_gpio(70, 0)
17:05:12 < majestic> [ gpio] set_gpio@25 set_gpio(68, 0)
```

Попробовал после вручную (после сброса состояния ночного режима) и это снова повторилось:

`echo 1 > /sys/class/gpio/gpio68/value`

В общем, какая то непонятка с gpio. Я еще поэкспериментирую немного...

**Comment by flyrouter** [comment]
Done
