### ISSUE TITLE
DW-1080ip20se 3516ev100+ unknown imx307

### ISSUE THREAD

**Issue by leksmax** [OpenIPC/majestic#88]
# Required information

 * Camera board id:matrix MT-DW1080IP20SE
 * OpenIPC version:master+a2e2e7b3, 2022-11-26
 * Commit:a2e2e7b3
 * Branch:
 * Tag:
 * installation method: (by manual https://github.com/OpenIPC/openipc-2.1/wiki/install_hisi or another)
 * modified majestic.yaml: yes/no
 * cat /dev/kmsg https://pastebin.com/RVNJaEbj
 * killall majestic
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
   Core dump file from /tmp/ , e.g. /tmp/majestic.806.11.1619707881.core
             https://pastebin.com/wXxznp7k
# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Expectations

# Steps to reproduce
![photo_2022-12-05_11-40-28](https://user-images.githubusercontent.com/29253291/205569965-31c02bfb-b8c1-48c4-8e1a-891b934eb0bd.jpg)
![photo_2022-12-05_11-40-29](https://user-images.githubusercontent.com/29253291/205569969-63f57fb3-39ac-4e8b-90cf-892a1380404c.jpg)
![photo_2022-12-05_11-40-33](https://user-images.githubusercontent.com/29253291/205569975-9d310526-eb84-4f60-9504-4c09779e2607.jpg)
![photo_2022-12-05_11-40-36](https://user-images.githubusercontent.com/29253291/205569980-96d2b315-9d6e-4dac-8dae-1c5bf02fc987.jpg)
![photo_2022-12-05_11-58-31](https://user-images.githubusercontent.com/29253291/205569983-1dc9e0e5-1bbe-4d49-b0ce-a6a8aeaed1e8.jpg)
![photo_2022-12-05_11-58-36](https://user-images.githubusercontent.com/29253291/205569986-7835d62b-db7c-4fe9-8bc9-e40825bd4e50.jpg)
![photo_2022-12-05_11-58-41](https://user-images.githubusercontent.com/29253291/205569991-8fb0f3c9-2caf-49c0-9d06-4562c6cb23bf.jpg)

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant log output (`logread -f`)
 - [ ] majestic.yaml configuration (`cat /etc/majestic.yaml`)

**Comment by widgetii** [comment]
Issue resolved in TG group
