### ISSUE TITLE
HLS only works on web browser(s)

### ISSUE THREAD

**Issue by brainstorm** [OpenIPC/majestic#90]
Using HLS.js and connecting to "torturelabs.com" subdomain, Majestic's HLS endpoint does not work with iOS VLC nor HLS-specific apps, i.e:

![image](https://user-images.githubusercontent.com/175587/206411665-1e5235c2-91b7-4d39-94de-576d846f3b32.png)

**Comment by widgetii** [comment]
What's a Sofia on the screen? Please describe step by step how to reproduce this issue with your specific data on any iOS device (which applications should be installed and so on)

**Comment by widgetii** [comment]
http://openipc.local/hls is an HTML page and I doubt any player except browser can do something with it
http://openipc.local/video.m3u8 is a correct URL for HLS video (this is described in wiki)

**Comment by brainstorm** [comment]
Thanks! VLC playback is a bit erratic but it ends up working well :)

**Comment by brainstorm** [comment]
Perhaps https://openipc.org/majestic-endpoints should list the .m3u8 url instead of the hls one as browsers and apps understand the playlist file format right away.

In other words, what does HLS.js provide here that the raw playlist doesn't?
