### ISSUE TITLE
Change size of OSD font 

### ISSUE THREAD

**Issue by scramatte** [OpenIPC/majestic#91]
# Required information

 * Camera board id: hi3518ev200 (hi3516cv200 family), ov9732, 16 MB Flash
 * OpenIPC version: 2.2.11.26-lite

# Issue description

How can I change the size of OSD text ?

**Comment by FlyRouter** [comment]
[https://github-com.translate.goog/OpenIPC/firmware/issues/155?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp](https://github-com.translate.goog/OpenIPC/firmware/issues/155?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp)

**Comment by widgetii** [comment]
Dup
